using System;using System.IO;using System.Net;using System.Net.Sockets;using System.Text;using System.Threading.Tasks;using System.Collections.Generic;using System.Reflection;using BabelManager;
class DiagnosticsTests {
 sealed class Fixture:IDisposable {
  public readonly string Root=Path.Combine(Path.GetTempPath(),"BTMirror-diagnostics-"+Guid.NewGuid().ToString("N"));public Settings Settings;public string Addons,Gi,PackageVpk;
  public Fixture(){string game=Path.Combine(Root,"Deadlock"),install=Path.Combine(Root,"BabelTower"),package=Path.Combine(install,"BabelTower-108");Directory.CreateDirectory(Path.Combine(game,"game","bin","win64"));File.WriteAllText(Path.Combine(game,"game","bin","win64","deadlock.exe"),"");Addons=Path.Combine(game,"game","citadel","addons");Directory.CreateDirectory(Addons);Directory.CreateDirectory(Path.Combine(package,"core"));Directory.CreateDirectory(Path.Combine(package,"portable-node"));Directory.CreateDirectory(Path.Combine(package,"config"));File.WriteAllText(Path.Combine(package,"core","bridge_server.js"),"");File.WriteAllText(Path.Combine(package,"portable-node","node.exe"),"");File.WriteAllText(Path.Combine(package,"README.md"),"版本:1.0.8");PackageVpk=Path.Combine(package,"pak01_dir.vpk");Vpk(PackageVpk,0);File.Copy(PackageVpk,Path.Combine(Addons,"pak01_dir.vpk"));Gi=Path.Combine(game,"game","citadel","gameinfo.gi");File.WriteAllText(Gi,"\"GameInfo\" { FileSystem { SearchPaths { Game citadel/addons Game citadel Game core } } }");Settings=new Settings{GameRoot=game,InstallRoot=install,CurrentFolder=package};}
  public void Dispose(){string full=Path.GetFullPath(Root);if(!full.StartsWith(Path.GetFullPath(Path.GetTempPath()),StringComparison.OrdinalIgnoreCase)||!Path.GetFileName(full).StartsWith("BTMirror-diagnostics-"))throw new Exception("unsafe fixture cleanup");Directory.Delete(full,true);}
 }
 static void Vpk(string file,byte extra){byte[] tree=Encoding.UTF8.GetBytes("vjs_c\0panorama/scripts\0lingua_chat\0");using(var b=new BinaryWriter(File.Create(file))){b.Write((uint)0x55AA1234);b.Write((uint)1);b.Write((uint)tree.Length);b.Write(tree);b.Write(extra);}}
 sealed class FakeRuntime:IBridgeRuntime {public bool Owned,Foreign;public string Stopped="",Started="";public CheckResult Result=new CheckResult{Local=true,Translation=true,Text="连接正常",Key="42"};public bool HasOwned(string p){return Owned;}public void Stop(string p){Stopped=p;Owned=false;}public void Start(string p,Settings s,Action<string> log){Started=p;if(Foreign)throw new Exception("port occupied");Owned=true;}public CheckResult Check(string p,Action<string> log,Action<bool,string> local){return Result;}}
 static int passed,failed;
 static void Test(string name,Action action){try{action();passed++;Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.WriteLine("FAIL "+name+": "+(e.InnerException??e).Message);}}
 static void Assert(bool value,string message){if(!value)throw new Exception(message);}
 static string ReceiveRequest(TcpListener listener){using(var client=listener.AcceptTcpClient())using(var stream=client.GetStream()){var data=new List<byte>();int c;while((c=stream.ReadByte())>=0){data.Add((byte)c);int n=data.Count;if(n>=4&&data[n-4]==13&&data[n-3]==10&&data[n-2]==13&&data[n-1]==10)break;}string headers=Encoding.ASCII.GetString(data.ToArray());int length=0;foreach(var line in headers.Split('\n'))if(line.StartsWith("Content-Length:",StringComparison.OrdinalIgnoreCase))length=Int32.Parse(line.Split(':')[1].Trim());byte[] body=new byte[length];int offset=0;while(offset<length){int read=stream.Read(body,offset,length-offset);if(read==0)break;offset+=read;}byte[] response=Encoding.UTF8.GetBytes("{\"ok\":true,\"translation\":\"连接检查成功\"}");byte[] prefix=Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: "+response.Length+"\r\nConnection: close\r\n\r\n");stream.Write(prefix,0,prefix.Length);stream.Write(response,0,response.Length);return Encoding.UTF8.GetString(body);}}
 static void Main(){
  Test("online test avoids dictionary and repeating cache",()=>{var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();try{int port=((IPEndPoint)listener.LocalEndpoint).Port;string[] texts=new string[2];for(int i=0;i<2;i++){var server=Task.Run(()=>ReceiveRequest(listener));Bridge.Request(port,"/api/v1/test",true);string json=server.GetAwaiter().GetResult();texts[i]=Convert.ToString(Core.Json().Deserialize<Dictionary<string,object>>(json)["text"]);}Assert(texts[0].Length>40,"test text can still hit short-word dictionary");Assert(texts[0]!=texts[1],"repeated request can hit cache");}finally{listener.Stop();}});
  Test("installation diagnostics available",()=>Assert(typeof(Core).Assembly.GetType("BabelManager.Installation")!=null,"installation inspection is missing"));
  Test("connection evidence can expire",()=>Assert(typeof(Core).Assembly.GetType("BabelManager.Connectivity")!=null,"connection evidence never expires"));
  Test("unchanged English is not online translation success",()=>{var method=typeof(Bridge).GetMethod("TranslationValid");Assert(method!=null,"translation validation is missing");Assert(!(bool)method.Invoke(null,new object[]{"hello","hello"}),"unchanged response was accepted");Assert(!(bool)method.Invoke(null,new object[]{"Test sentence","network failed"}),"English error was accepted");Assert((bool)method.Invoke(null,new object[]{"Test sentence","测试句子"}),"Chinese translation was rejected");});
  Test("matching package and prioritized mount pass without changing files",()=>{using(var f=new Fixture()){string before=File.ReadAllText(f.Gi);var r=Installation.Inspect(f.Settings);Assert(r.Ready,r.Summary);Assert(File.ReadAllText(f.Gi)==before,"inspect changed gameinfo");Assert(Directory.GetFiles(f.Addons).Length==1,"inspect created a file");}});
  Test("missing addon is diagnosed without creating its folder",()=>{using(var f=new Fixture()){File.Delete(Path.Combine(f.Addons,"pak01_dir.vpk"));Directory.Delete(f.Addons);var r=Installation.Inspect(f.Settings);Assert(!r.Ready&&!r.Vpk,"missing addon accepted");Assert(!Directory.Exists(f.Addons),"read-only check created addons");}});
  Test("different package version is rejected",()=>{using(var f=new Fixture()){Vpk(Path.Combine(f.Addons,"pak01_dir.vpk"),1);Assert(!Installation.Inspect(f.Settings).Ready,"mismatched VPK accepted");}});
  Test("duplicate Babel vpks are diagnosed and preserved",()=>{using(var f=new Fixture()){File.Copy(f.PackageVpk,Path.Combine(f.Addons,"pak19_dir.vpk"));Assert(!Installation.Inspect(f.Settings).Ready,"duplicate VPK accepted");Assert(File.Exists(Path.Combine(f.Addons,"pak19_dir.vpk")),"inspection deleted duplicate");}});
  Test("another mod vpk does not count as Babel duplicate",()=>{using(var f=new Fixture()){File.WriteAllText(Path.Combine(f.Addons,"pak99_dir.vpk"),"other mod");Assert(Installation.Inspect(f.Settings).Ready,"unrelated mod blocked launch");}});
  Test("commented mount does not pass",()=>Assert(!Installation.HasAddonsMount("GameInfo { FileSystem { SearchPaths { // Game citadel/addons\n Game citadel } } }"),"comment accepted"));
  Test("mount in unrelated section does not pass",()=>Assert(!Installation.HasAddonsMount("GameInfo { Tools { SearchPaths { Game citadel/addons } } FileSystem { SearchPaths { Game citadel } } }"),"wrong section accepted"));
  Test("addons after base game does not pass",()=>Assert(!Installation.HasAddonsMount("GameInfo { FileSystem { SearchPaths { Game citadel Game citadel/addons } } }"),"wrong priority accepted"));
  Test("quoted Windows slashes and gameinfo relative paths pass",()=>{Assert(Installation.HasAddonsMount("\"GameInfo\" { \"FileSystem\" { \"SearchPaths\" { \"Game\" \"citadel\\addons\" \"Game\" \"citadel\" } } }"),"Windows slashes rejected");Assert(Installation.HasAddonsMount("GameInfo { FileSystem { SearchPaths { Game+Mod |gameinfo_path|addons Game citadel } } }"),"relative mount rejected");});
  Test("broken configuration produces diagnostic rather than crash",()=>{using(var f=new Fixture()){File.WriteAllText(f.Gi,"GameInfo { FileSystem { SearchPaths {");Assert(!Installation.Inspect(f.Settings).Ready,"broken configuration accepted");}});
  Test("old asynchronous probe cannot overwrite new check",()=>{var c=new Connectivity();c.ChangeContext("one");long revision=c.Revision;c.RecordCheck(new CheckResult{Local=true,Translation=true,Text="成功",Key="new"},DateTime.UtcNow);Assert(!c.ApplyProbe(new ProbeResult{Local=false},revision,DateTime.UtcNow)&&c.Local,"stale probe overwrote full check");});
  Test("bridge going offline invalidates translation evidence",()=>{var c=new Connectivity();DateTime now=DateTime.UtcNow;c.RecordCheck(new CheckResult{Local=true,Translation=true,Key="7"},now);c.ApplyProbe(new ProbeResult{Local=false},c.Revision,now.AddSeconds(1));Assert(!c.TranslationFresh(now.AddSeconds(1)),"offline bridge kept green translation");});
  Test("new bridge process invalidates previous translation test",()=>{var c=new Connectivity();DateTime now=DateTime.UtcNow;c.RecordCheck(new CheckResult{Local=true,Translation=true,Key="7"},now);c.ApplyProbe(new ProbeResult{Local=true,Key="8"},c.Revision,now.AddSeconds(1));Assert(!c.TranslationFresh(now.AddSeconds(1)),"new process inherited old translation success");});
  Test("translation result expires despite healthy probes",()=>{var c=new Connectivity();DateTime now=DateTime.UtcNow;c.RecordCheck(new CheckResult{Local=true,Translation=true,Key="7"},now);DateTime later=now.AddMinutes(11);c.ApplyProbe(new ProbeResult{Local=true,Key="7"},c.Revision,later);Assert(!c.TranslationFresh(later),"old API result stays green indefinitely");});
  Test("failed refresh and stale health remove green status",()=>{var c=new Connectivity();DateTime now=DateTime.UtcNow;c.RecordCheck(new CheckResult{Local=true,Translation=true,Key="7"},now);Assert(!c.LocalFresh(now.AddSeconds(46))&&!c.TranslationFresh(now.AddSeconds(46)),"stale health accepted");c.RecordCheck(new CheckResult{Local=true,Translation=false,Key="7"},now.AddSeconds(47));Assert(!c.TranslationFresh(now.AddSeconds(47)),"failure preserved previous translation success");});
  Test("changing package invalidates previous evidence",()=>{var c=new Connectivity();DateTime now=DateTime.UtcNow;c.ChangeContext("one");long revision=c.Revision;c.RecordCheck(new CheckResult{Local=true,Translation=true,Key="7"},now);c.ChangeContext("two");Assert(!c.Known&&!c.TranslationFresh(now)&&!c.ApplyProbe(new ProbeResult{Local=true,Key="7"},revision,now),"changed package inherited results");});
  Test("manual repair restarts only selected package and returns new result",()=>{using(var f=new Fixture()){var runtime=new FakeRuntime{Owned=true};var result=Recovery.Run(f.Settings,true,s=>{},(ok,error)=>{},runtime);Assert(result.Translation&&runtime.Stopped==f.Settings.CurrentFolder&&runtime.Started==f.Settings.CurrentFolder,"repair failed or touched another package");Assert(Installation.Inspect(f.Settings).Ready,"repair changed game files");}});
  Test("foreign port owner is never stopped by repair",()=>{using(var f=new Fixture()){var runtime=new FakeRuntime{Owned=false,Foreign=true};bool failedPort=false;try{Recovery.Run(f.Settings,true,s=>{},null,runtime);}catch{failedPort=true;}Assert(failedPort&&runtime.Stopped=="","foreign bridge was stopped");}});
  Test("check without restart does not stop healthy bridge",()=>{using(var f=new Fixture()){var runtime=new FakeRuntime{Owned=true};Recovery.Run(f.Settings,false,s=>{},null,runtime);Assert(runtime.Stopped=="","readiness check restarted running bridge");}});
  Test("HTTP listener process must actually belong to selected bridge",()=>{var owns=typeof(Bridge).GetMethod("PortOwned");Assert(owns!=null,"port listener identity is missing");Assert(!(bool)owns.Invoke(null,new object[]{new[]{7},new[]{8}}),"another bridge listener accepted");Assert((bool)owns.Invoke(null,new object[]{new[]{7,9},new[]{7}}),"selected bridge rejected");Assert(!(bool)owns.Invoke(null,new object[]{new[]{7},new[]{7,8}}),"ambiguous listener accepted");});
  Test("native listener lookup finds only our temporary endpoint",()=>{var lookup=typeof(Bridge).GetMethod("ListeningPids");Assert(lookup!=null,"listener lookup is missing");var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();try{int port=((IPEndPoint)listener.LocalEndpoint).Port;var ids=(List<int>)lookup.Invoke(null,new object[]{port});Assert(ids.Count==1&&ids[0]==System.Diagnostics.Process.GetCurrentProcess().Id,"incorrect listener PID");}finally{listener.Stop();}});
  Test("healthy polling preserves failed online test evidence",()=>{var c=new Connectivity();DateTime now=DateTime.UtcNow;c.RecordCheck(new CheckResult{Local=true,Translation=false,Key="7",Error="API quota exceeded"},now);c.ApplyProbe(new ProbeResult{Local=true,Key="7"},c.Revision,now.AddSeconds(15));var error=typeof(Connectivity).GetField("TranslationError");Assert(error!=null&&Convert.ToString(error.GetValue(c))=="API quota exceeded","health probe erased online failure");Assert(!c.TranslationFresh(now.AddSeconds(15)),"online failure became success");});
  Test("disabled game uplink prevents ready status",()=>{using(var f=new Fixture()){File.WriteAllText(Path.Combine(f.Settings.CurrentFolder,"config","config.json"),"{\"gameLogTail\":false,\"port\":8791}");Assert(!Installation.Inspect(f.Settings).Ready,"disabled game log uplink accepted");}});
  Test("108 bridge on another port is diagnosed",()=>{using(var f=new Fixture()){File.WriteAllText(Path.Combine(f.Settings.CurrentFolder,"config","config.json"),"{\"gameLogTail\":true,\"port\":9000}");Assert(!Installation.Inspect(f.Settings).Ready,"108 hardcoded game port mismatch accepted");}});
  Console.WriteLine("RESULT "+passed+" passed, "+failed+" failed");Environment.ExitCode=failed==0?0:1;
 }
}
