using System;using System.IO;using System.Linq;using System.Reflection;using System.Text;using System.Threading;using System.Collections.Generic;using BabelManager;
class OnlineUpdateTests {
 static int passed;static Type client;
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);passed++;Console.WriteLine("PASS "+message);}
 static object Call(string name,params object[] args){var method=client.GetMethod(name);if(method==null)throw new Exception("expected feature missing: "+name);try{return method.Invoke(null,args);}catch(TargetInvocationException e){throw e.InnerException;}}
 static object Field(object value,string name){return value.GetType().GetField(name).GetValue(value);}
 static void Reject(Action action,string message){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,message);}
 static object Release(string tag,bool preview=false,bool draft=false,string name=null,string digest="sha256:ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",string url=null){string version=tag.TrimStart('v');name=name??"BabelTower-"+version+"-win64.zip";return new{tag_name=tag,prerelease=preview,draft=draft,body="release notes",published_at="2026-10-05T10:00:00Z",html_url="https://github.com/c1375rick/BabelTower/releases/tag/"+tag,assets=new[]{new{name=name,size=3,browser_download_url=url??"https://github.com/c1375rick/BabelTower/releases/download/"+tag+"/"+name,digest=digest}}};}
 static object Select(params object[] releases){return Call("SelectLatest",Core.Json().Serialize(releases));}
 static void Main(){string scratch=Path.Combine(Path.GetTempPath(),"BTOnline-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(scratch);try{
  client=typeof(Core).Assembly.GetType("BabelManager.OfficialUpdates");Check(client!=null,"official update service is available in mirror");
  var latest=Select(Release("v1.0.9"),Release("v1.0.10"),Release("v2.0.0",true),Release("v3.0.0",false,true));Check((string)Field(latest,"Tag")=="v1.0.10","semantic ordering selects 1.0.10 and excludes draft or prerelease");
  Reject(()=>Select(Release("v1.0.10",false,false,"pak01_dir.vpk")),"standalone VPK never substitutes for complete portable package");
  Reject(()=>Select(Release("v1.0.10",false,false,"Source code.zip")),"source archive never substitutes for complete portable package");
  Reject(()=>Select(Release("v1.0.10",false,false,null,null)),"automatic update requires published SHA256 digest");
  Reject(()=>Select(Release("v1.0.10",false,false,null,null,"https://example.com/mod.zip")),"external asset URL rejected before any download");
  Reject(()=>Select(Release("v1.0.10",false,false,null,"sha256:abc","https://github.com/other/Repo/releases/download/v1.0.10/mod.zip")),"another repository cannot become the update source");
  Reject(()=>Select(Release("v1.0.9"),Release("v1.0.10",false,false,"pak01_dir.vpk")),"incomplete newest release does not silently install an older version");
  string pkg=Path.Combine(scratch,"pkg");Directory.CreateDirectory(pkg);File.WriteAllText(Path.Combine(pkg,"VERSION"),"1.0.9\n");Check((bool)Call("IsNewer",latest,pkg),"1.0.10 upgrades an installed 1.0.9 package");File.WriteAllText(Path.Combine(pkg,"VERSION"),"1.0.10");Check(!(bool)Call("IsNewer",latest,pkg),"same installed version is not offered as an update");File.WriteAllText(Path.Combine(pkg,"VERSION"),"2.0.0");Check(!(bool)Call("IsNewer",latest,pkg),"online update never downgrades a newer installed version");
  var release=Select(Release("v1.0.8"));Func<Uri,CancellationToken,Stream> good=(uri,token)=>new MemoryStream(Encoding.UTF8.GetBytes("abc"));
  string file=(string)Call("Download",release,scratch,CancellationToken.None,null,good);Check(File.ReadAllText(file)=="abc","verified download commits the actual complete bytes");
  Call("VerifyArchive",release,file);Check(true,"cached archive can be reverified before deferred installation");File.WriteAllText(file,"abd");Reject(()=>Call("VerifyArchive",release,file),"tampered cached archive is rejected before deferred installation");File.WriteAllText(file,"abc");
  Func<Uri,CancellationToken,Stream> bad=(uri,token)=>new MemoryStream(Encoding.UTF8.GetBytes("abd"));Reject(()=>Call("Download",release,scratch,CancellationToken.None,null,bad),"wrong digest prevents completed archive from being committed");
  Func<Uri,CancellationToken,Stream> shortBody=(uri,token)=>new MemoryStream(Encoding.UTF8.GetBytes("ab"));Reject(()=>Call("Download",release,scratch,CancellationToken.None,null,shortBody),"truncated response cannot become an installable archive");
  Func<Uri,CancellationToken,Stream> largeBody=(uri,token)=>new MemoryStream(Encoding.UTF8.GetBytes("abcd"));Reject(()=>Call("Download",release,scratch,CancellationToken.None,null,largeBody),"oversized response rejected at download boundary");
  using(var cancel=new CancellationTokenSource()){cancel.Cancel();Reject(()=>Call("Download",release,scratch,cancel.Token,null,good),"cancelled request cannot start an archive download");}
  Func<Uri,CancellationToken,Stream> interrupted=(uri,token)=>new BrokenStream();Reject(()=>Call("Download",release,scratch,CancellationToken.None,null,interrupted),"interrupted transfer leaves no completed archive");
  Check(Directory.GetFiles(scratch,"*.part",SearchOption.AllDirectories).Length==0,"failed and cancelled downloads clean partial files");Check(File.ReadAllText(file)=="abc","failed retries preserve an earlier verified download");
  var sessionType=typeof(Core).Assembly.GetType("BabelManager.ModDownloadSession");Check(sessionType!=null,"download session remembers game occupancy at start");var duringGame=Activator.CreateInstance(sessionType,new object[]{true});Check(!(bool)sessionType.GetMethod("CanInstallAutomatically").Invoke(duringGame,new object[]{false}),"exiting during transfer still requires an explicit install click");var idle=Activator.CreateInstance(sessionType,new object[]{false});Check((bool)sessionType.GetMethod("CanInstallAutomatically").Invoke(idle,new object[]{false})&&!(bool)sessionType.GetMethod("CanInstallAutomatically").Invoke(idle,new object[]{true}),"idle download auto-installs only when game remains stopped");
  var cacheType=typeof(Core).Assembly.GetType("BabelManager.DownloadCache");Check(cacheType!=null,"verified pending download cache is available");cacheType.GetMethod("Save").Invoke(null,new object[]{scratch,release,file});Check((string)cacheType.GetMethod("Find").Invoke(null,new object[]{scratch,release})==file,"verified download is rediscovered after launcher restart");File.WriteAllText(file,"abd");Check((string)cacheType.GetMethod("Find").Invoke(null,new object[]{scratch,release})=="","tampered persisted download is not offered for installation");File.WriteAllText(file,"abc");
  Console.WriteLine("ONLINE RESULT "+passed+" passed");
 }catch(Exception e){Console.WriteLine("FAIL "+e.Message);Environment.ExitCode=1;}finally{string full=Path.GetFullPath(scratch);if(full.StartsWith(Path.GetFullPath(Path.GetTempPath()),StringComparison.OrdinalIgnoreCase)&&Path.GetFileName(full).StartsWith("BTOnline-test-"))Directory.Delete(full,true);}}
 class BrokenStream:MemoryStream {public override int Read(byte[] buffer,int offset,int count){throw new IOException("fixture: disconnected transfer");}}
}
