using System;using System.IO;using System.IO.Compression;using System.Reflection;using System.Text;using System.Collections.Generic;using BabelManager;
class PackageUpdateTests {
 static int passed;static Type installer;
 static void Check(bool ok,string m){if(!ok)throw new Exception(m);passed++;Console.WriteLine("PASS "+m);}
 static object Install(Settings s,string zip,IBridgeRuntime runtime,Func<bool> running,List<string> logs){try{return installer.GetMethod("Install").Invoke(null,new object[]{s,zip,runtime,running,new Action<string>(logs.Add),null});}catch(TargetInvocationException e){System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(e.InnerException).Throw();throw;}}
 static void Reject(Action a,string m){bool rejected=false;try{a();}catch{rejected=true;}Check(rejected,m);}
 const string GI="\"GameInfo\"\n{\n \"FileSystem\"\n {\n  // keep the user's existing entries\n  \"SearchPaths\"\n  {\n   Game citadel\n   Game core\n  }\n }\n}\n";
 static void Package(string path,string version){Directory.CreateDirectory(Path.Combine(path,"core"));Directory.CreateDirectory(Path.Combine(path,"portable-node"));Directory.CreateDirectory(Path.Combine(path,"config"));File.WriteAllText(Path.Combine(path,"core","bridge_server.js"),"fixture");File.WriteAllText(Path.Combine(path,"portable-node","node.exe"),"fixture");File.WriteAllText(Path.Combine(path,"VERSION"),version);File.WriteAllText(Path.Combine(path,"config","config.example.json"),"{\"port\":8791,\"gameLogTail\":true}");using(var b=new BinaryWriter(File.Create(Path.Combine(path,"pak01_dir.vpk")))){byte[] tree=Encoding.UTF8.GetBytes("vjs_c\0panorama/scripts\0lingua_chat\0"+version);b.Write((uint)0x55AA1234);b.Write((uint)1);b.Write((uint)tree.Length);b.Write(tree);}}
 class Runtime:IBridgeRuntime {public bool Fail;public bool HasOwned(string folder){return true;}public void Stop(string folder){}public void Start(string folder,Settings s,Action<string> log){Core.WriteGameLog(folder,s);}public CheckResult Check(string folder,Action<string> log,Action<bool,string> local){return new CheckResult{Local=true,Translation=!Fail,Error=Fail?"fixture translation offline":"",Key="fixture"};}}
 class Fixture:IDisposable {public string Root,Game,InstallRoot,Old,Zip,Gi,Addon;public Settings Settings;public List<string> Logs=new List<string>();
  public Fixture(){Root=Path.Combine(Path.GetTempPath(),"BTPackage-test-"+Guid.NewGuid().ToString("N"));Game=Path.Combine(Root,"Deadlock");InstallRoot=Path.Combine(Root,"BabelTower");Old=Path.Combine(InstallRoot,"BabelTower-108");Directory.CreateDirectory(Path.Combine(Game,"game","bin","win64"));File.WriteAllText(Path.Combine(Game,"game","bin","win64","deadlock.exe"),"");Directory.CreateDirectory(Path.Combine(Game,"game","citadel","addons"));Gi=Path.Combine(Game,"game","citadel","gameinfo.gi");File.WriteAllText(Gi,GI);Package(Old,"1.0.8");File.WriteAllText(Path.Combine(Old,"old-only.txt"),"old");Addon=Path.Combine(Game,"game","citadel","addons","pak16_dir.vpk");File.Copy(Path.Combine(Old,"pak01_dir.vpk"),Addon);File.WriteAllText(Path.Combine(Path.GetDirectoryName(Addon),"pak17_dir.vpk"),"other mod");string package=Path.Combine(Root,"new-package");Package(package,"1.0.9");Zip=Path.Combine(Root,"BabelTower-1.0.9-win64.zip");ZipFile.CreateFromDirectory(package,Zip);Settings=new Settings{GameRoot=Game,InstallRoot=InstallRoot,CurrentFolder=Old,VpkPath=Addon};Core.SettingsPath=Path.Combine(Root,"profile","settings.json");Core.BackupsDir=Path.Combine(Root,"backups");Core.Save(Settings);}
  public void Dispose(){string resolved=Path.GetFullPath(Root);if(!resolved.StartsWith(Path.GetFullPath(Path.GetTempPath()),StringComparison.OrdinalIgnoreCase)||!Path.GetFileName(resolved).StartsWith("BTPackage-test-"))throw new Exception("unsafe fixture cleanup");Directory.Delete(Root,true);}}
 static void Main(){try{installer=typeof(Core).Assembly.GetType("BabelManager.PackageInstaller");Check(installer!=null,"transactional package installer is available in mirror");
  using(var f=new Fixture()){string vpk=Convert.ToBase64String(File.ReadAllBytes(f.Addon));Reject(()=>Install(f.Settings,f.Zip,new Runtime(),()=>true,f.Logs),"running game prevents package replacement");Check(Directory.Exists(f.Old)&&Convert.ToBase64String(File.ReadAllBytes(f.Addon))==vpk&&File.ReadAllText(f.Gi)==GI,"game occupancy preserves package VPK and loading config");}
  using(var f=new Fixture()){string vpk=Convert.ToBase64String(File.ReadAllBytes(f.Addon));Reject(()=>Install(f.Settings,f.Zip,new Runtime{Fail=true},()=>false,f.Logs),"failed translation test cancels package transaction");Check(f.Settings.CurrentFolder==f.Old&&Directory.Exists(f.Old)&&Convert.ToBase64String(File.ReadAllBytes(f.Addon))==vpk&&File.ReadAllText(f.Gi)==GI,"translation failure preserves previous files and selection");Check(!Directory.Exists(Path.Combine(f.InstallRoot,"BabelTower-109")),"failed staged package is cleaned without deleting old version");}
  using(var f=new Fixture()){Install(f.Settings,f.Zip,new Runtime(),()=>false,f.Logs);Check(f.Settings.CurrentFolder==Path.Combine(f.InstallRoot,"BabelTower-109")&&Installation.Inspect(f.Settings).Ready,"whole package update repairs mount and passes installation inspection");Check(!Directory.Exists(f.Old)&&!File.Exists(Path.Combine(f.Settings.CurrentFolder,"old-only.txt")),"old package removed only after successful validation without migration");Check(File.ReadAllText(f.Gi).Contains("keep the user's existing entries")&&File.ReadAllText(f.Gi).Contains("Game core"),"mount repair preserves unrelated entries and comments");Check(File.ReadAllText(Path.Combine(Path.GetDirectoryName(f.Addon),"pak17_dir.vpk"))=="other mod","unrelated VPK is preserved during online package install");Check(Core.Load().CurrentFolder==f.Settings.CurrentFolder,"mirror profile commits only the validated package");Check(Directory.GetFiles(Core.BackupsDir,"gameinfo.gi",SearchOption.AllDirectories).Length==1,"loading configuration recovery copy is retained");}
  using(var f=new Fixture()){string vpk=Convert.ToBase64String(File.ReadAllBytes(f.Addon));Core.SettingsPath=Path.Combine(f.Root,"occupied-profile");Directory.CreateDirectory(Core.SettingsPath);Reject(()=>Install(f.Settings,f.Zip,new Runtime(),()=>false,f.Logs),"profile commit failure rolls back whole installation");Check(File.ReadAllText(f.Gi)==GI&&Convert.ToBase64String(File.ReadAllBytes(f.Addon))==vpk&&Directory.Exists(f.Old)&&f.Settings.CurrentFolder==f.Old,"rollback restores loading config VPK and old package");}
  using(var f=new Fixture()){File.WriteAllText(f.Gi,"broken {");Reject(()=>Install(f.Settings,f.Zip,new Runtime(),()=>false,f.Logs),"malformed loading config aborts before installation");Check(Directory.Exists(f.Old)&&File.ReadAllText(f.Gi)=="broken {","malformed user config is not overwritten");}
  using(var f=new Fixture()){string fresh=Path.Combine(f.InstallRoot,"BabelTower-109");Package(fresh,"1.0.9");string duplicate=Path.Combine(Path.GetDirectoryName(f.Addon),"pak18_dir.vpk");File.Copy(Path.Combine(f.Old,"pak01_dir.vpk"),duplicate);FileStream occupied=null,temporaryOccupied=null;Exception failure=null;try{Core.Commit(f.Settings,fresh,()=>{},true,()=>{occupied=new FileStream(f.Addon,FileMode.Open,FileAccess.Read,FileShare.None);temporaryOccupied=new FileStream(f.Addon+".bt-new",FileMode.Create,FileAccess.ReadWrite,FileShare.None);f.Settings.CurrentFolder=fresh;throw new IOException("fixture interrupted commit");});}catch(Exception e){failure=e;}finally{if(occupied!=null)occupied.Dispose();if(temporaryOccupied!=null)temporaryOccupied.Dispose();}Check(failure!=null&&failure.GetType().GetField("RecoveryComplete")!=null,"temporary cleanup failure cannot hide structured incomplete recovery");Check(File.Exists(duplicate)&&f.Settings.CurrentFolder==f.Old,"blocked VPK restoration still restores other files and resets selection");}
  using(var f=new Fixture()){Core.SettingsPath=Path.Combine(f.Root,"occupied-profile");Directory.CreateDirectory(Core.SettingsPath);Exception failure=null;Action<string> logger=message=>{f.Logs.Add(message);if(message.Contains("已补齐 addons"))File.AppendAllText(f.Gi,"\n// concurrent external edit\n");};try{installer.GetMethod("Install").Invoke(null,new object[]{f.Settings,f.Zip,new Runtime(),new Func<bool>(()=>false),logger,null});}catch(TargetInvocationException e){failure=e.InnerException;}Check(failure!=null&&File.ReadAllText(f.Gi).Contains("concurrent external edit"),"rollback preserves concurrent loading config changes");Check(Directory.Exists(Path.Combine(f.InstallRoot,"BabelTower-109"))&&Directory.Exists(f.Old),"incomplete recovery retains both package trees for repair");}
  Console.WriteLine("PACKAGE RESULT "+passed+" passed");
 }catch(Exception e){Console.WriteLine("FAIL "+e);Environment.ExitCode=1;}}
}
