using System;using System.IO;using System.IO.Compression;using System.Linq;using System.Reflection;using System.Security.Cryptography;using System.Text;using System.Diagnostics;using BabelManager;
class SelfUpdateTests {
 static int passed;static void Check(bool ok,string m){if(!ok)throw new Exception(m);passed++;Console.WriteLine("PASS "+m);}
 static object Call(Type type,string method,params object[] args){var member=type.GetMethod(method);if(member==null)throw new Exception("expected feature missing: "+method);try{return member.Invoke(null,args);}catch(TargetInvocationException e){System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(e.InnerException).Throw();throw;}}
 static void Reject(Action action,string m){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,m);}
 static string Hash(string path){using(var hash=SHA256.Create())using(var stream=File.OpenRead(path))return BitConverter.ToString(hash.ComputeHash(stream)).Replace("-","").ToLowerInvariant();}
 static object Release(string tag,string name,string digest,long size,bool draft=false,string url=null){return new{tag_name=tag,prerelease=true,draft=draft,body="launcher release",published_at="2026-10-05T10:00:00Z",html_url="https://github.com/alloywr147/BabelTowerLauncher/releases/tag/"+tag,assets=new[]{new{name=name,size=size,browser_download_url=url??"https://github.com/alloywr147/BabelTowerLauncher/releases/download/"+tag+"/"+name,digest=digest}}};}
 static OfficialRelease Select(params object[] releases){return (OfficialRelease)Call(typeof(OfficialUpdates),"SelectLauncher",Core.Json().Serialize(releases));}
 class Fixture:IDisposable {public string Root,Target,Payload,Zip,ExeName="巴别塔启动器-在线更新镜像.exe";public OfficialRelease Release;
  public Fixture(string binary){Root=Path.Combine(Path.GetTempPath(),"BTSelf-test-"+Guid.NewGuid().ToString("N"));Target=Path.Combine(Root,"mirror");Payload=Path.Combine(Root,"payload");Directory.CreateDirectory(Path.Combine(Target,"assets"));Directory.CreateDirectory(Path.Combine(Target,"tools"));Directory.CreateDirectory(Path.Combine(Target,"data"));File.WriteAllText(Path.Combine(Target,ExeName),"old application");File.WriteAllText(Path.Combine(Target,ExeName+".config"),"old runtime config");File.WriteAllText(Path.Combine(Target,"assets","app.ico"),"old icon");File.WriteAllText(Path.Combine(Target,"tools","7z.exe"),"old tool");File.WriteAllText(Path.Combine(Target,"data","settings.json"),"personal settings");Directory.CreateDirectory(Path.Combine(Payload,"assets"));Directory.CreateDirectory(Path.Combine(Payload,"tools"));File.Copy(binary,Path.Combine(Payload,"巴别塔启动器.exe"));File.WriteAllText(Path.Combine(Payload,"巴别塔启动器.exe.config"),"new runtime config");File.WriteAllText(Path.Combine(Payload,"assets","app.ico"),"new icon");File.WriteAllText(Path.Combine(Payload,"tools","7z.exe"),"new tool");File.WriteAllText(Path.Combine(Payload,"tools","7z.dll"),"new library");Refresh();}
  public void Refresh(){Zip=Path.Combine(Root,"BabelTowerLauncher-1.5-win64.zip");if(File.Exists(Zip))File.Delete(Zip);ZipFile.CreateFromDirectory(Payload,Zip);Release=Select(ReleaseMetadata());}
  object ReleaseMetadata(){return SelfUpdateTests.Release("v1.5",Path.GetFileName(Zip),"sha256:"+Hash(Zip),new FileInfo(Zip).Length);}
  public void Dispose(){string full=Path.GetFullPath(Root);if(!full.StartsWith(Path.GetFullPath(Path.GetTempPath()),StringComparison.OrdinalIgnoreCase)||!Path.GetFileName(full).StartsWith("BTSelf-test-"))throw new Exception("unsafe fixture cleanup");for(int attempt=0;;attempt++){try{Directory.Delete(full,true);break;}catch(IOException){if(attempt==49)throw;System.Threading.Thread.Sleep(100);}catch(UnauthorizedAccessException){if(attempt==49)throw;System.Threading.Thread.Sleep(100);}}}}
 static void Main(string[] args){try{
  var latest=Select(Release("v1.3.1","BabelTowerLauncher-1.3.1-win64.zip","sha256:"+new string('a',64),3),Release("v1.5","BabelTowerLauncher-1.5-win64.zip","sha256:"+new string('b',64),3));Check(latest.Tag=="v1.5","launcher updates read own repository and include published testing releases");
  Reject(()=>Select(Release("v1.5","BabelTowerLauncher-1.5-win64.zip","sha256:"+new string('a',64),3,false,"https://github.com/c1375rick/BabelTower/releases/download/v1.5/BabelTowerLauncher-1.5-win64.zip")),"launcher and Mod download sources cannot be mixed");Reject(()=>Select(Release("v1.5","Source code.zip","sha256:"+new string('a',64),3)),"launcher update never accepts GitHub source archive");
  var shortRelease=Select(Release("v1.5","BabelTowerLauncher-1.5-win64.zip","sha256:"+new string('a',64),3));Check(shortRelease.Version==new Version(1,5,0),"two-component launcher tags normalize for binary version comparison");
  var ordered=Select(Release("v1.9","BabelTowerLauncher-1.9-win64.zip","sha256:"+new string('a',64),3),Release("v1.10","BabelTowerLauncher-1.10-win64.zip","sha256:"+new string('a',64),3));Check(ordered.Tag=="v1.10","launcher versions 1.9 and 1.10 use numeric ordering");
  Reject(()=>Select(Release("v1.5","BabelTowerLauncher-1.5.0-win64.zip","sha256:"+new string('a',64),3)),"launcher package name must match the published tag spelling");
  Type updater=typeof(Core).Assembly.GetType("BabelManager.SelfUpdater"),files=typeof(Core).Assembly.GetType("BabelManager.SelfUpdateFiles");Check(updater!=null&&files!=null,"staged self-update and file transaction are available");
  using(var f=new Fixture(args[0])){var plan=Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,Process.GetCurrentProcess().Id);Check(File.ReadAllText(Path.Combine(f.Target,f.ExeName))=="old application","staging self-update does not replace the running program");Call(files,"Apply",plan);Check(Hash(Path.Combine(f.Target,f.ExeName))==Hash(Path.Combine(f.Payload,"巴别塔启动器.exe")),"self-update replaces current mirror executable while preserving its launch name");Check(File.ReadAllText(Path.Combine(f.Target,f.ExeName+".config"))=="new runtime config"&&File.ReadAllText(Path.Combine(f.Target,"assets","app.ico"))=="new icon","self-update replaces associated runtime config and assets");Check(File.ReadAllText(Path.Combine(f.Target,"data","settings.json"))=="personal settings","self-update preserves existing user profile");Check(!File.Exists(Path.Combine(f.Target,"巴别塔启动器.exe")),"self-update does not create a second executable alias");}
  using(var f=new Fixture(args[0])){var plan=Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,Process.GetCurrentProcess().Id);using(var occupied=new FileStream(Path.Combine(f.Target,"tools","7z.exe"),FileMode.Open,FileAccess.Read,FileShare.Read)){Reject(()=>Call(files,"Apply",plan),"occupied program resource aborts self-update");Check(File.ReadAllText(Path.Combine(f.Target,"assets","app.ico"))=="old icon"&&File.ReadAllText(Path.Combine(f.Target,f.ExeName))=="old application","failed self-update restores files already replaced");}Check(File.ReadAllText(Path.Combine(f.Target,"data","settings.json"))=="personal settings","failed self-update also preserves profile");}
  using(var f=new Fixture(args[0])){Directory.CreateDirectory(Path.Combine(f.Payload,"data"));File.WriteAllText(Path.Combine(f.Payload,"data","settings.json"),"unexpected packaged profile");f.Refresh();Reject(()=>Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,Process.GetCurrentProcess().Id),"self-update rejects packages carrying user data");}
  using(var f=new Fixture(args[0])){File.Delete(Path.Combine(f.Payload,"巴别塔启动器.exe.config"));f.Refresh();Reject(()=>Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,Process.GetCurrentProcess().Id),"incomplete launcher package cannot be prepared");}
  using(var f=new Fixture(args[0])){f.Release.Version=new Version(1,3,4);f.Release.Tag="v1.3.4";f.Release.Name="BabelTowerLauncher-1.3.4-win64.zip";f.Release.DownloadUrl="https://github.com/alloywr147/BabelTowerLauncher/releases/download/v1.3.4/"+f.Release.Name;Reject(()=>Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,Process.GetCurrentProcess().Id),"launcher binary version must match release metadata");}
  using(var f=new Fixture(args[0])){var plan=(SelfUpdatePlan)Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,Process.GetCurrentProcess().Id);File.WriteAllText(Path.Combine(plan.JobDirectory,"backup"),"occupied backup directory");Exception failure=null;try{Call(files,"Apply",plan);}catch(Exception e){failure=e;}Check(failure is SelfUpdateFailure&&((SelfUpdateFailure)failure).RecoveryComplete,"failure before first replacement reports original application fully preserved");Check(File.ReadAllText(Path.Combine(f.Target,f.ExeName))=="old application","backup preparation failure does not change any application file");}
  using(var f=new Fixture(args[0])){File.Copy(args[0],Path.Combine(f.Target,f.ExeName),true);File.WriteAllText(Path.Combine(f.Target,f.ExeName+".config"),"<configuration/>");File.WriteAllText(Path.Combine(f.Payload,"巴别塔启动器.exe.config"),"<configuration/>");f.Refresh();File.Copy(args[1],Path.Combine(f.Target,"tools","BabelTowerUpdater.exe"));File.Copy(args[1]+".config",Path.Combine(f.Target,"tools","BabelTowerUpdater.exe.config"));string gate=Path.Combine(f.Root,"exit-parent.txt");using(var parent=Process.Start(new ProcessStartInfo(Path.Combine(f.Target,f.ExeName),Core.Quote(gate)){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden,WorkingDirectory=f.Target})){try{var plan=(SelfUpdatePlan)Call(updater,"Prepare",f.Release,f.Zip,f.Target,f.ExeName,parent.Id);Call(updater,"Start",plan);Check(File.Exists(Path.Combine(plan.JobDirectory,"ready.txt"))&&!parent.HasExited,"helper handoff waits for verified readiness before parent exits");Check(!File.Exists(Path.Combine(f.Target,"restart-marker.txt"))&&File.ReadAllText(Path.Combine(f.Target,"assets","app.ico"))=="old icon","helper cannot replace files while parent remains running");File.WriteAllText(gate,"exit");parent.WaitForExit(10000);string marker=Path.Combine(f.Target,"restart-marker.txt");var wait=Stopwatch.StartNew();while(!File.Exists(marker)&&wait.ElapsedMilliseconds<10000)System.Threading.Thread.Sleep(50);Check(File.Exists(marker)&&File.ReadAllText(Path.Combine(plan.JobDirectory,"result.txt")).Trim() == "SUCCESS","background helper replaces isolated fixture after exit and automatically reopens it");Check(File.ReadAllText(Path.Combine(f.Target,"data","settings.json"))=="personal settings","full helper handoff preserves fixture user settings");System.Threading.Thread.Sleep(200);}finally{if(!parent.HasExited){File.WriteAllText(gate,"exit");parent.WaitForExit(10000);}}}}
  using(var f=new Fixture(args[0])){File.Copy(args[0],Path.Combine(f.Target,f.ExeName),true);File.WriteAllText(Path.Combine(f.Target,f.ExeName+".config"),"<configuration/>");File.WriteAllText(Path.Combine(f.Payload,"巴别塔启动器.exe.config"),"<configuration/>");f.Refresh();File.Copy(args[1],Path.Combine(f.Target,"tools","BabelTowerUpdater.exe"));File.Copy(args[1]+".config",Path.Combine(f.Target,"tools","BabelTowerUpdater.exe.config"));string gate=Path.Combine(f.Root,"exit-parent.txt");using(var parent=Process.Start(new ProcessStartInfo(Path.Combine(f.Target,f.ExeName),Core.Quote(gate)){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden})){try{var plan=SelfUpdater.Prepare(f.Release,f.Zip,f.Target,f.ExeName,parent.Id);using(var token=new System.Threading.CancellationTokenSource()){token.Cancel();Reject(()=>SelfUpdater.StartCancelable(plan,token.Token),"cancelled handoff never starts a background updater");Check(String.IsNullOrEmpty(plan.HelperExecutable),"pre-handoff cancellation does not create executable helper copy");}SelfUpdater.Start(plan);SelfUpdater.CancelHandoff(plan);foreach(var helper in Process.GetProcessesByName(Path.GetFileNameWithoutExtension(plan.HelperExecutable)))using(helper){Check(helper.WaitForExit(5000),"cancel after readiness stops helper before any replacement");}Check(!parent.HasExited&&File.ReadAllText(Path.Combine(f.Target,"assets","app.ico"))=="old icon","cancelled handoff leaves parent open and original files unchanged");File.WriteAllText(gate,"exit");parent.WaitForExit(10000);Check(!File.Exists(Path.Combine(f.Target,"restart-marker.txt"))&&!File.Exists(Path.Combine(plan.JobDirectory,"result.txt")),"later parent exit cannot resume a cancelled self-update");}finally{if(!parent.HasExited){File.WriteAllText(gate,"exit");parent.WaitForExit(10000);}}}}
  Console.WriteLine("SELF UPDATE RESULT "+passed+" passed; only isolated silent fixtures launched");
 }catch(Exception e){Console.WriteLine("FAIL "+e);Environment.ExitCode=1;}}
}
