using System;using System.Drawing;using System.Drawing.Imaging;using System.Linq;using System.Reflection;using System.Windows.Forms;using BabelManager;
class SoftwareUiTests {
 static int passed;static void Check(bool ok,string message){if(!ok)throw new Exception(message);passed++;Console.WriteLine("PASS "+message);}
 static object Field(MainWindow w,string name){return typeof(MainWindow).GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(w);}
 static void Call(MainWindow w,string name){var method=typeof(MainWindow).GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance);if(method==null)throw new Exception("expected feature missing: "+name);method.Invoke(w,null);}
 static Control[] All(Control c){return c.Controls.Cast<Control>().SelectMany(x=>new[]{x}.Concat(All(x))).ToArray();}
 static void Hidden(Control c){typeof(Control).GetMethod("CreateControl",BindingFlags.NonPublic|BindingFlags.Instance,null,new[]{typeof(bool)},null).Invoke(c,new object[]{true});foreach(Control child in c.Controls)Hidden(child);}
 [STAThread]static void Main(string[] args){try{Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);using(var w=new MainWindow()){
  Call(w,"ShowSoftwareUpdate");Check(All(w).OfType<Button>().Any(b=>b.Text=="检查软件更新"),"software updates have a separate page and check action");Check(All(w).OfType<Label>().Any(l=>l.Text.Contains("alloywr147")),"software page identifies launcher repository rather than Mod repository");Check(!((Button)Field(w,"officialDownload")).Enabled,"software installation requires verified release metadata");
  var field=typeof(MainWindow).GetField("launcherRelease",BindingFlags.NonPublic|BindingFlags.Instance);field.SetValue(w,new OfficialRelease{Version=new Version(1,3,1),Tag="v1.3.1"});Call(w,"RenderSoftware");Check(!((Button)Field(w,"officialDownload")).Enabled,"older GitHub launcher cannot overwrite newer mirror");field.SetValue(w,new OfficialRelease{Version=new Version(1,5,0),Tag="v1.5",Size=3000000});Call(w,"RenderSoftware");Check(((Button)Field(w,"officialDownload")).Enabled&&((Button)Field(w,"officialDownload")).Text.Contains("重启"),"newer software action states automatic restart");
  Hidden(w);w.PerformLayout();foreach(var button in All(w).OfType<Button>())Check(button.Right<=button.Parent.ClientSize.Width&&button.Bottom<=button.Parent.ClientSize.Height,"software action fits parent: "+button.Text);var body=(Panel)Field(w,"body");Check(body.Controls.Cast<Control>().All(c=>c.Bottom<=body.ClientSize.Height),"software cards fit viewport");Check(!((System.Windows.Forms.Timer)Field(w,"heartbeat")).Enabled,"software UI verification does not poll or launch bridge");if(args.Length>0)using(var bitmap=new Bitmap(w.Width,w.Height)){w.DrawToBitmap(bitmap,new Rectangle(0,0,bitmap.Width,bitmap.Height));bitmap.Save(args[0],ImageFormat.Png);}
 }Console.WriteLine("SOFTWARE UI RESULT "+passed+" passed");}catch(Exception e){Console.WriteLine("FAIL "+(e.InnerException??e).Message);Environment.ExitCode=1;}}
}
