using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Microsoft.Win32;

namespace BabelManager {
 public class DetectionResult {public List<string> Games=new List<string>(),Packages=new List<string>();public string Game="",Package="",InstallRoot="";}
 public static class Discovery {
  static bool ValidGame(string p){try{return Core.IsGame(p);}catch{return false;}}
  static bool Linked(string p){try{return (File.GetAttributes(p)&FileAttributes.ReparsePoint)!=0;}catch{return true;}}
  static List<string> Dirs(string p){try{return Directory.GetDirectories(p).Where(d=>!Linked(d)).ToList();}catch{return new List<string>();}}
  static string Unescape(string s){return s.Replace("\\\\","\\").Replace("\\\"","\"");}
  static List<string> Unique(IEnumerable<string> paths){return paths.Where(p=>!String.IsNullOrWhiteSpace(p)).Distinct(StringComparer.OrdinalIgnoreCase).ToList();}
  public static List<string> LibraryPaths(string vdf){var list=new List<string>();foreach(Match m in Regex.Matches(vdf,@"""path""\s*""((?:\\.|[^""\\])*)""",RegexOptions.IgnoreCase)){string p=Unescape(m.Groups[1].Value);if(Path.IsPathRooted(p))list.Add(p);}foreach(Match m in Regex.Matches(vdf,@"^\s*""\d+""\s*""((?:\\.|[^""\\])*)""",RegexOptions.Multiline)){string p=Unescape(m.Groups[1].Value);if(Path.IsPathRooted(p))list.Add(p);}return Unique(list);}
  public static List<string> FindGames(IEnumerable<string> libraries){var games=new List<string>();foreach(string lib in Unique(libraries)){try{string common=Path.Combine(lib,"steamapps","common");string game=Path.Combine(common,"Deadlock");if(ValidGame(game))games.Add(game);string manifest=Path.Combine(lib,"steamapps","appmanifest_1422450.acf");if(File.Exists(manifest)){var m=Regex.Match(File.ReadAllText(manifest),@"""installdir""\s*""((?:\\.|[^""\\])*)""",RegexOptions.IgnoreCase);if(m.Success){string p=Core.Child(common,Unescape(m.Groups[1].Value));if(ValidGame(p))games.Add(p);}}}catch{}}return Unique(games);}
  public static List<string> FindPackages(IEnumerable<string> roots){var found=new List<string>();int visited=0;foreach(string root in Unique(roots)){var queue=new Queue<Tuple<string,int>>();queue.Enqueue(Tuple.Create(root,0));while(queue.Count>0&&visited<2500){var x=queue.Dequeue();if(!Directory.Exists(x.Item1)||Linked(x.Item1))continue;if(Path.GetFileName(x.Item1).StartsWith(".bt-stage-",StringComparison.OrdinalIgnoreCase))continue;visited++;try{if(Core.IsPackage(x.Item1)){found.Add(x.Item1);continue;}}catch{}if(x.Item2<2)foreach(string child in Dirs(x.Item1))queue.Enqueue(Tuple.Create(child,x.Item2+1));}}return Unique(found);}
  static Version Rank(string p){try{foreach(string name in new[]{"VERSION","README.md","安装使用说明.txt"}){string file=Path.Combine(p,name);if(!File.Exists(file))continue;var m=Regex.Match(File.ReadAllText(file),@"(?:版本\s*[:：]?\s*|^\s*v?)(\d+)\.(\d+)\.(\d+)",RegexOptions.Multiline);if(m.Success)return new Version(Int32.Parse(m.Groups[1].Value),Int32.Parse(m.Groups[2].Value),Int32.Parse(m.Groups[3].Value));}string v=Core.VersionOf(Path.GetFileName(p),p);if(v.Length>=3)return new Version(Int32.Parse(v.Substring(0,1)),Int32.Parse(v.Substring(1,1)),Int32.Parse(v.Substring(2)));}catch{}return new Version(0,0,0);}
  public static string PreferredPackage(List<string> found,string saved){string selected=found.FirstOrDefault(p=>p.Equals(saved,StringComparison.OrdinalIgnoreCase));return selected??found.OrderByDescending(Rank).ThenBy(p=>p,StringComparer.OrdinalIgnoreCase).FirstOrDefault()??"";}
  public static string SuggestInstallRoot(Settings saved,string package,string game){if(!String.IsNullOrWhiteSpace(saved.InstallRoot))return saved.InstallRoot;if(!String.IsNullOrEmpty(package)){string parent=Path.GetDirectoryName(package);if(parent!=null&&Core.Full(parent).Length>3)return parent;return Path.Combine(Path.GetPathRoot(package),"BabelTower");}if(!String.IsNullOrEmpty(game))return Path.Combine(Path.GetPathRoot(game),"BabelTower");return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"BabelTower");}
  static List<string> DriveRoots(){var roots=new List<string>();foreach(var drive in DriveInfo.GetDrives()){try{if(drive.DriveType==DriveType.Fixed&&drive.IsReady)roots.Add(drive.RootDirectory.FullName);}catch{}}return roots;}
  static List<string> SteamDirectories(List<string> drives){var paths=new List<string>();foreach(var hive in new[]{RegistryHive.CurrentUser,RegistryHive.LocalMachine})foreach(var view in new[]{RegistryView.Registry64,RegistryView.Registry32}){try{using(var baseKey=RegistryKey.OpenBaseKey(hive,view))using(var key=baseKey.OpenSubKey(@"Software\Valve\Steam")){if(key==null)continue;foreach(string name in new[]{"SteamPath","InstallPath"}){string value=key.GetValue(name) as string;if(!String.IsNullOrEmpty(value))paths.Add(value);}string exe=key.GetValue("SteamExe") as string;if(!String.IsNullOrEmpty(exe))paths.Add(Path.GetDirectoryName(exe));}}catch{}}
   foreach(string root in drives){paths.Add(Path.Combine(root,"Steam"));paths.Add(Path.Combine(root,"Program Files (x86)","Steam"));paths.Add(Path.Combine(root,"Program Files","Steam"));}return Unique(paths).Where(p=>Directory.Exists(p)).ToList();}
  public static DetectionResult Detect(Settings saved){var result=new DetectionResult();var drives=DriveRoots();var libraries=new List<string>();foreach(string steam in SteamDirectories(drives)){libraries.Add(steam);foreach(string file in new[]{Path.Combine(steam,"steamapps","libraryfolders.vdf"),Path.Combine(steam,"config","libraryfolders.vdf")}){try{if(File.Exists(file))libraries.AddRange(LibraryPaths(File.ReadAllText(file)));}catch{}}}foreach(string root in drives){libraries.Add(Path.Combine(root,"SteamLibrary"));libraries.Add(Path.Combine(root,"Steam"));libraries.Add(Path.Combine(root,"Games","SteamLibrary"));}
   result.Games=FindGames(libraries);if(ValidGame(saved.GameRoot))result.Games.Insert(0,saved.GameRoot);result.Games=Unique(result.Games);result.Game=result.Games.FirstOrDefault()??"";
   var bases=new List<string>{saved.CurrentFolder,saved.InstallRoot};foreach(string root in drives){bases.Add(Path.Combine(root,"BabelTower"));bases.Add(Path.Combine(root,"巴别塔"));bases.AddRange(Dirs(root).Where(d=>Regex.IsMatch(Path.GetFileName(d),@"babel|巴别塔",RegexOptions.IgnoreCase)));}
   string profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);bases.Add(Path.Combine(profile,"Downloads"));bases.Add(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory));bases.Add(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"BabelTower"));
   result.Packages=FindPackages(bases);result.Package=PreferredPackage(result.Packages,saved.CurrentFolder);result.InstallRoot=SuggestInstallRoot(saved,result.Package,result.Game);return result;
  }
 }
}
