using System;using System.Diagnostics;using System.Drawing;using System.IO;using System.Threading;using System.Threading.Tasks;using System.Windows.Forms;
namespace BabelManager {
 public partial class MainWindow {
  bool softwarePage;OfficialRelease launcherRelease;
  void ShowSoftwareUpdate(){if(busy)return;RhineRoute("software");ClearBody();softwarePage=true;importPage=diagnosticPage=false;
   body.Controls.Add(LabelAt("启动器软件更新",32,24,720,42,25,null,true));body.Controls.Add(LabelAt("当前启动器  /  "+SelfUpdater.VersionLabel(SelfUpdater.CurrentVersion),34,75,720,26,10,Muted));settingsButton=ButtonAt("←  返回",800,34,168,42,false,()=>{if(Core.IsGame(settings.GameRoot)&&Directory.Exists(settings.InstallRoot))ShowMain();else ShowSetup();});body.Controls.Add(settingsButton);
   var card=new Card{Location=new Point(32,120),Size=new Size(936,280),AccessibleName="启动器在线更新"};card.Controls.Add(LabelAt("从启动器仓库更新",24,18,760,34,18,null,true));card.Controls.Add(LabelAt("GitHub  /  alloywr147 · BabelTowerLauncher",24,60,880,28,10,Muted));officialStatus=LabelAt("尚未检查软件版本",24,105,888,44,12,Muted);card.Controls.Add(officialStatus);
   officialCheck=ButtonAt("检查软件更新",24,164,168,44,false,CheckSoftware);officialDownload=ButtonAt("下载并重启更新",208,164,252,44,true,DownloadSoftware);officialNotes=ButtonAt("更新说明",476,164,138,44,false,()=>ShowReleaseNotes(launcherRelease));officialCancel=ButtonAt("取消下载",772,164,140,44,false,()=>{if(onlineCancellation!=null)onlineCancellation.Cancel();});foreach(var b in new[]{officialCheck,officialDownload,officialNotes,officialCancel})card.Controls.Add(b);downloadProgress=new ModernProgressBar{Location=new Point(24,226),Size=new Size(888,6),Minimum=0,Maximum=100,AccessibleName="启动器下载进度"};card.Controls.Add(downloadProgress);downloadStatus=LabelAt("",24,242,888,29,9,Muted);card.Controls.Add(downloadStatus);body.Controls.Add(card);
   var note=new Card{Location=new Point(32,424),Size=new Size(936,98)};note.Controls.Add(LabelAt("校验完成后自动退出、替换并重新打开",24,20,875,32,14,null,true));note.Controls.Add(LabelAt("保留启动器配置；此操作只更新当前启动器文件。",24,60,875,27,10,Muted));body.Controls.Add(note);
   body.Controls.Add(LabelAt("更新记录",34,546,900,27,10,Muted,true));var logs=new Card{Location=new Point(32,581),Size=new Size(936,98)};logBox=new ListBox{Location=new Point(16,12),Size=new Size(901,72),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Ink,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9)};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderSoftware();
  }
  void RenderSoftware(){if(officialStatus==null||officialStatus.IsDisposed)return;officialCheck.Enabled=!busy;officialCancel.Enabled=busy&&onlineCancellation!=null;officialCancel.Visible=onlineCancellation!=null;officialNotes.Enabled=!busy&&launcherRelease!=null;officialDownload.Enabled=!busy&&launcherRelease!=null&&launcherRelease.Version>SelfUpdater.CurrentVersion;officialDownload.Text="下载并重启更新";officialStatus.Text=launcherRelease==null?"尚未检查软件版本":launcherRelease.Version>SelfUpdater.CurrentVersion?"可用版本  "+SelfUpdater.VersionLabel(launcherRelease.Version)+"  ·  "+(launcherRelease.Size/1024d/1024d).ToString("F1")+" MB":"无需更新  ·  仓库版本 "+SelfUpdater.VersionLabel(launcherRelease.Version);officialStatus.ForeColor=launcherRelease!=null&&launcherRelease.Version<=SelfUpdater.CurrentVersion?Green:Ink;}
  async void CheckSoftware(){if(busy)return;onlineCancellation=new CancellationTokenSource();SetBusy(true);officialStatus.Text="正在检查软件版本…";try{launcherRelease=await Task.Run(()=>OfficialUpdates.GetLatestLauncher(onlineCancellation.Token));Log("启动器发布版本："+launcherRelease.Tag+" / "+launcherRelease.Name);downloadStatus.Text=launcherRelease.Version<=SelfUpdater.CurrentVersion?"当前版本无需更新。":"新版下载校验完成后将自动重启。";}catch(OperationCanceledException){downloadStatus.Text="检查已取消";}catch(Exception e){launcherRelease=null;downloadStatus.Text=e.Message;Log("检查失败："+e.Message);}finally{onlineCancellation.Dispose();onlineCancellation=null;SetBusy(false);}}
  async void DownloadSoftware(){if(busy||launcherRelease==null||launcherRelease.Version<=SelfUpdater.CurrentVersion)return;var release=launcherRelease;onlineCancellation=new CancellationTokenSource();SetBusy(true);downloadStatus.Text="正在准备软件更新…";SelfUpdatePlan plan=null;try{string cache=Path.Combine(Core.DataDir,"software-downloads");string archive=await Task.Run(()=>DownloadCache.Find(cache,release));if(String.IsNullOrEmpty(archive)){downloadProgress.Value=0;var progress=new Progress<DownloadProgress>(p=>{if(onlineCancellation!=null&&downloadProgress!=null&&!downloadProgress.IsDisposed){downloadProgress.Value=p.Percent;downloadStatus.Text=p.Percent+"%  ·  "+(p.Received/1024d/1024d).ToString("F1")+" / "+(p.Total/1024d/1024d).ToString("F1")+" MB";}});archive=await Task.Run(()=>OfficialUpdates.Download(release,cache,onlineCancellation.Token,p=>((IProgress<DownloadProgress>)progress).Report(p),null));await Task.Run(()=>DownloadCache.Save(cache,release,archive));}onlineCancellation.Token.ThrowIfCancellationRequested();downloadProgress.Value=100;downloadStatus.Text="校验通过，正在暂存软件文件…";string target=AppDomain.CurrentDomain.BaseDirectory,exe=Path.GetFileName(typeof(MainWindow).Assembly.Location);int pid=Process.GetCurrentProcess().Id;plan=await Task.Run(()=>SelfUpdater.Prepare(release,archive,target,exe,pid));onlineCancellation.Token.ThrowIfCancellationRequested();Log("软件文件校验通过，等待后台更新程序就绪。");officialCancel.Enabled=false;await Task.Run(()=>SelfUpdater.StartCancelable(plan,onlineCancellation.Token));onlineCancellation.Token.ThrowIfCancellationRequested();busy=false;Application.Exit();}catch(OperationCanceledException){if(plan!=null)try{SelfUpdater.CancelHandoff(plan);}catch(Exception cancelError){Log(cancelError.Message);}if(downloadStatus!=null&&!downloadStatus.IsDisposed)downloadStatus.Text="软件更新已取消，当前文件未变。";}catch(Exception e){if(!IsDisposed){downloadStatus.Text=e.Message;Log("软件更新未启动："+e.Message);Error(e.Message);}}finally{onlineCancellation.Dispose();onlineCancellation=null;if(!IsDisposed)SetBusy(false);}}
 }
}

