using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace BabelManager {
 public partial class MainWindow:Form {
  Color Navy{get{return Theme.Background;}}Color Blue{get{return Theme.Accent;}}Color Green{get{return Theme.Success;}}Color Ink{get{return Theme.Text;}}Color Muted{get{return Theme.Muted;}}Button themeToggle;
  Settings settings;Panel body;Label local,translation,version;ListBox logBox;Button update,launch,settingsButton;bool busy,detecting,importPage,diagnosticPage,monitoring;Action pendingDetection;
  OfficialRelease officialRelease;string officialArchive="",downloadedTag="";CancellationTokenSource onlineCancellation;Label officialStatus,downloadStatus;ProgressBar downloadProgress;Button officialCheck,officialDownload,officialNotes,officialCancel;
  readonly ToolTip hints=new ToolTip{AutoPopDelay=12000};readonly Connectivity connectivity=new Connectivity();readonly System.Windows.Forms.Timer heartbeat=new System.Windows.Forms.Timer{Interval=15000};InstallationResult installation;Label installationStatus,gameNotice;Button diagnosticButton,repairButton;
  public MainWindow(){settings=Core.Load()??new Settings();Theme.SetDark(ThemePreferences.LoadDark());Text="巴别塔启动器";ClientSize=new Size(1000,760);MinimumSize=new Size(1016,799);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Microsoft YaHei UI",10);BackColor=Theme.Background;AutoScaleMode=AutoScaleMode.Dpi;
   string icon=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","app.ico");if(File.Exists(icon))Icon=new Icon(icon);ShowIcon=false;
   var header=new Panel{Dock=DockStyle.Top,Height=72,BackColor=Theme.Surface};
   header.Controls.Add(LabelAt("巴别塔启动器",32,15,470,36,22,Theme.Text,true));
   header.Controls.Add(LabelAt("VERSION  /  1.5",604,28,228,27,10,Theme.Muted));
   themeToggle=ButtonAt("",846,17,122,38,false,ToggleTheme);header.Controls.Add(themeToggle);RenderThemeToggle();HandleCreated+=(o,e)=>Theme.ApplyChrome(this);Activated+=(o,e)=>QueueStartupOffer();
   header.Paint+=(o,e)=>{using(var p=new Pen(Theme.Text,1))e.Graphics.DrawLine(p,32,66,968,66);using(var b=new SolidBrush(Theme.Accent))e.Graphics.FillRectangle(b,32,66,86,4);};Controls.Add(header);
   body=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Background};Controls.Add(body);body.BringToFront();heartbeat.Tick+=(o,e)=>PollBridge();FormClosed+=(o,e)=>{if(startupCancellation!=null)startupCancellation.Cancel();heartbeat.Stop();heartbeat.Dispose();hints.Dispose();};Shown+=(o,e)=>{if(RhineTestMode)return;heartbeat.Start();PollBridge();var action=pendingDetection;pendingDetection=null;if(action!=null)action();CheckStartupUpdates();};FormClosing+=(o,e)=>{if(busy){e.Cancel=true;if(onlineCancellation!=null){onlineCancellation.Cancel();if(downloadStatus!=null)downloadStatus.Text="正在取消，完成后可关闭窗口。";}else MessageBox.Show(this,"正在执行检查或安装，请等待完成后关闭。","处理中");}};
   if(Core.IsGame(settings.GameRoot)&&Directory.Exists(settings.InstallRoot))ShowMain();else ShowSetup();
  }
  void RenderThemeToggle(){themeToggle.Text=Theme.IsDark?"浅色模式":"深色模式";themeToggle.AccessibleName="切换主题（当前"+(Theme.IsDark?"深色":"浅色")+"）";hints.SetToolTip(themeToggle,"切换明暗主题，自动记住选择。");}
  void ToggleTheme(){var previous=Theme.Current;Theme.SetDark(!Theme.IsDark);SuspendLayout();try{Theme.Recolor(this,previous);RenderThemeToggle();Theme.ApplyChrome(this);}finally{ResumeLayout(false);}try{ThemePreferences.SaveDark(Theme.IsDark);}catch(Exception error){Log("主题已切换，但偏好未能保存："+error.Message);}}
  Label LabelAt(string text,int x,int y,int width,int height,int size=10,Color? color=null,bool bold=false){return new Label{BackColor=Color.Transparent,Text=text,Location=new Point(x,y),Size=new Size(width,height),ForeColor=color??Ink,Font=new Font(Font.FontFamily,size,bold?FontStyle.Bold:FontStyle.Regular)};}
  Button ButtonAt(string text,int x,int y,int w,int h,bool primary,Action click){var b=new ModernButton{Text=text,Location=new Point(x,y),Size=new Size(w,h),Primary=primary,BackColor=Theme.Surface,ForeColor=primary?Theme.ButtonInk:Ink,AccessibleName=text};b.Click+=(o,e)=>click();return b;}
  string PickFolder(string caption,string selected=""){using(var d=new FolderBrowserDialog{Description=caption,SelectedPath=selected,ShowNewFolderButton=true})return d.ShowDialog(this)==DialogResult.OK?d.SelectedPath:null;}
  void ClearBody(){foreach(Control c in body.Controls.Cast<Control>().ToArray())c.Dispose();softwarePage=false;local=translation=installationStatus=gameNotice=null;logBox=null;launch=update=settingsButton=diagnosticButton=repairButton=null;officialStatus=downloadStatus=null;downloadProgress=null;officialCheck=officialDownload=officialNotes=officialCancel=null;}
  void ShowSetup(){RhineRoute("settings");ClearBody();diagnosticPage=importPage=false;body.Controls.Add(LabelAt(Core.IsGame(settings.GameRoot)?"路径设置":"首次设置",30,22,650,38,20,null,true));
   ComboBox game=null,current=null;TextBox root=null;var status=LabelAt("",32,454,874,48,10,Muted);body.Controls.Add(status);
   game=ChoiceField("游戏目录",108,settings.GameRoot,"Deadlock 根目录，包含 game 文件夹。",()=>DetectPaths(game,root,current,status,"game"));
   root=Field("巴别塔安装目录",223,settings.InstallRoot,"用于保存巴别塔各版本。");
   current=ChoiceField("已有版本（可选）",338,settings.CurrentFolder,"未安装可留空。",()=>DetectPaths(game,root,current,status,"mod"));
   var detectAll=ButtonAt("一键自动检测",740,23,166,38,false,()=>DetectPaths(game,root,current,status,"all"));detectAll.Tag="detect";body.Controls.Add(detectAll);
   var save=ButtonAt("保存",32,516,245,48,true,()=>{if(detecting)return;try{var next=new Settings{GameRoot=game.Text.Trim(),InstallRoot=root.Text.Trim(),CurrentFolder=current.Text.Trim()};Core.ValidateSettings(next);if(!String.IsNullOrEmpty(next.CurrentFolder)&&(!Core.IsPackage(next.CurrentFolder)||!Core.Under(next.InstallRoot,next.CurrentFolder)))throw new Exception("已有版本必须是所选安装文件夹里面的完整巴别塔文件夹。请先把它移进去，再选择。");Directory.CreateDirectory(next.InstallRoot);if(!String.IsNullOrEmpty(next.CurrentFolder)){var vpks=Core.GameVpks(next);next.VpkPath=vpks.FirstOrDefault()??"";}Core.Save(next);settings=next;ShowMain();StartupSettingsSaved();}catch(Exception ex){Error(ex.Message);}});save.Tag="detect";body.Controls.Add(save);body.Controls.Add(ButtonAt("软件更新",756,516,150,48,false,ShowSoftwareUpdate));
   if(Core.IsGame(settings.GameRoot))body.Controls.Add(ButtonAt("返回",300,516,100,48,false,()=>{if(!detecting)ShowMain();}));
   if(!RhineEnabled&&(!Core.IsGame(settings.GameRoot)||!Core.IsPackage(settings.CurrentFolder))){Action detect=()=>DetectPaths(game,root,current,status,"all");if(IsHandleCreated)BeginInvoke(detect);else pendingDetection=detect;}
  }
  ComboBox ChoiceField(string title,int y,string value,string help,Action detect){body.Controls.Add(LabelAt(title,32,y,550,28,12,null,true));var t=new ComboBox{BackColor=Theme.Surface,ForeColor=Theme.Text,FlatStyle=FlatStyle.Flat,Text=value,Location=new Point(32,y+37),Size=new Size(705,32),DropDownStyle=ComboBoxStyle.DropDown,AutoCompleteMode=AutoCompleteMode.SuggestAppend,AutoCompleteSource=AutoCompleteSource.ListItems,DropDownWidth=800};body.Controls.Add(t);var auto=ButtonAt("自动检测",606,y-3,130,31,false,detect);auto.Tag="detect";body.Controls.Add(auto);body.Controls.Add(ButtonAt("浏览…",756,y+33,150,37,false,()=>{string p=PickFolder(title,t.Text);if(p!=null)t.Text=p;}));body.Controls.Add(LabelAt(help,32,y+78,850,30,10,Muted));return t;}
  static void Choices(ComboBox box,string[] paths,string selected){box.Items.Clear();box.Items.AddRange(paths.Cast<object>().ToArray());box.Text=selected;}
  async void DetectPaths(ComboBox game,TextBox root,ComboBox current,Label status,string which){if(detecting||game==null||current==null||game.IsDisposed)return;detecting=true;foreach(Control b in body.Controls)if(Object.Equals(b.Tag,"detect"))b.Enabled=false;status.Text="正在检测 Steam 游戏库、常见安装位置与完整的巴别塔目录…";var inputs=new Settings{GameRoot=game.Text.Trim(),InstallRoot=root.Text.Trim(),CurrentFolder=current.Text.Trim()};try{var result=await Task.Run(()=>Discovery.Detect(inputs));if(game.IsDisposed||current.IsDisposed)return;if(which!="mod")Choices(game,result.Games.ToArray(),result.Game);if(which!="game"){Choices(current,result.Packages.ToArray(),result.Package);root.Text=result.InstallRoot;}status.Text="检测完成：找到 "+result.Games.Count+" 个游戏目录、"+result.Packages.Count+" 个巴别塔版本。"+(result.Games.Count==0?"未找到游戏，请手动浏览。":result.Packages.Count==0?"尚未找到已有版本，可先保存再导入压缩包。":"多个结果可在下拉框选择，确认后保存。");}catch(Exception ex){if(!status.IsDisposed)status.Text="检测未完成，可手动浏览："+ex.Message;}finally{detecting=false;QueueStartupOffer();if(!body.IsDisposed)foreach(Control b in body.Controls)if(Object.Equals(b.Tag,"detect"))b.Enabled=true;}}
  TextBox Field(string title,int y,string value,string help){body.Controls.Add(LabelAt(title,32,y,850,28,12,null,true));var t=new TextBox{BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.FixedSingle,Text=value,Location=new Point(32,y+37),Size=new Size(705,32),Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};body.Controls.Add(t);body.Controls.Add(ButtonAt("浏览…",756,y+33,150,37,false,()=>{string p=PickFolder(title,t.Text);if(p!=null)t.Text=p;}));body.Controls.Add(LabelAt(help,32,y+78,850,30,10,Muted));return t;}
  void ShowMain(){RhineRoute("home");ClearBody();importPage=diagnosticPage=false;SyncContext();
   var rail=new Panel{Location=new Point(24,26),Size=new Size(102,654),BackColor=Theme.Surface,Tag="navigation",AccessibleName="主导航"};
   rail.Paint+=(o,e)=>{using(var p=new Pen(Theme.Border))e.Graphics.DrawLine(p,101,0,101,654);};
   var home=ButtonAt("启动",10,20,80,48,true,()=>{if(!busy)ShowMain();});home.AccessibleName="启动（当前页面）";rail.Controls.Add(home);
   rail.Controls.Add(ButtonAt("更新",10,94,80,48,false,ShowImportPage));
   diagnosticButton=ButtonAt("诊断",10,168,80,48,false,ShowDiagnostics);rail.Controls.Add(diagnosticButton);
   settingsButton=ButtonAt("设置",10,242,80,48,false,ShowSetup);rail.Controls.Add(settingsButton);
   rail.Controls.Add(ButtonAt("软件更新",10,316,80,48,false,ShowSoftwareUpdate));
   rail.Controls.Add(ButtonAt("文件夹",10,584,80,48,false,()=>OpenFolder(settings.InstallRoot)));body.Controls.Add(rail);
   var name=LabelAt("DEADLOCK",150,23,818,70,44,Theme.Text,true);name.Font=new Font("Bahnschrift",44,FontStyle.Bold);body.Controls.Add(name);
   version=LabelAt("当前版本 / "+(String.IsNullOrEmpty(settings.CurrentFolder)?"尚未安装":Path.GetFileName(settings.CurrentFolder)),154,101,810,29,11,Theme.Text);body.Controls.Add(version);
   var check=new Card{Location=new Point(150,151),Size=new Size(818,240),Terrain=true,AccessibleName="连接状态"};
   check.Controls.Add(LabelAt("连接状态",24,19,410,32,17,Theme.Text,true));
   local=LabelAt("○  本地桥服务    尚未检查",24,74,436,32,12,Muted);check.Controls.Add(local);
   translation=LabelAt("○  在线翻译    尚未测试",24,129,436,32,12,Muted);check.Controls.Add(translation);
   installationStatus=LabelAt("○  安装文件    尚未检查",24,184,436,32,11,Muted);check.Controls.Add(installationStatus);
   check.Paint+=(o,e)=>{using(var p=new Pen(Theme.Border,1)){e.Graphics.DrawLine(p,24,113,450,113);e.Graphics.DrawLine(p,24,168,450,168);}};body.Controls.Add(check);
   var dock=new Card{Location=new Point(150,409),Size=new Size(818,96),Hero=true,AccessibleName="启动操作"};
   dock.Controls.Add(ButtonAt("桥日志",18,26,115,44,false,()=>{if(!String.IsNullOrEmpty(settings.CurrentFolder))OpenFolder(Path.Combine(settings.CurrentFolder,"logs"));}));dock.Controls.Add(ButtonAt("停止桥",147,26,115,44,false,StopBridge));
   launch=ButtonAt("检查并启动游戏  →",286,16,506,64,true,CheckLaunch);launch.Font=new Font(Font.FontFamily,18,FontStyle.Bold);dock.Controls.Add(launch);body.Controls.Add(dock);
   body.Controls.Add(LabelAt("运行记录",154,527,810,22,10,Muted,true));
   var logs=new Card{Location=new Point(150,560),Size=new Size(818,120)};logBox=new ListBox{Location=new Point(12,10),Size=new Size(790,98),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9),AccessibleName="运行记录"};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderChecks();RenderInstallation();RefreshLaunch();
   Log("游戏目录："+settings.GameRoot);Log("安装目录："+settings.InstallRoot);if(!String.IsNullOrEmpty(settings.CurrentFolder))Log("当前目录："+settings.CurrentFolder);
  }
  void ShowImportPage(){if(busy)return;RhineRoute("mod");ClearBody();importPage=true;diagnosticPage=false;launch=null;
   body.Controls.Add(LabelAt("Mod 版本更新",32,24,720,42,25,null,true));version=LabelAt("当前版本  /  "+(String.IsNullOrEmpty(settings.CurrentFolder)?"尚未安装":Path.GetFileName(settings.CurrentFolder)),34,75,700,26,10,Muted);body.Controls.Add(version);settingsButton=ButtonAt("←  返回启动",800,34,168,42,false,()=>{if(!busy)ShowMain();});body.Controls.Add(settingsButton);
   var online=new Card{Location=new Point(32,120),Size=new Size(936,244),AccessibleName="官方在线更新"};online.Controls.Add(LabelAt("从官方仓库更新",24,17,650,32,18,null,true));online.Controls.Add(LabelAt("GitHub  /  c1375rick · BabelTower",24,54,760,25,10,Muted));officialStatus=LabelAt("尚未检查官方版本",24,92,888,43,12,Muted);online.Controls.Add(officialStatus);
   officialCheck=ButtonAt("检查官方更新",24,146,168,44,false,CheckOfficial);officialDownload=ButtonAt("下载并更新",208,146,218,44,true,DownloadOfficial);officialNotes=ButtonAt("更新说明",442,146,138,44,false,ShowOfficialNotes);officialCancel=ButtonAt("取消下载",772,146,140,44,false,()=>{if(onlineCancellation!=null)onlineCancellation.Cancel();});foreach(var button in new[]{officialCheck,officialDownload,officialNotes,officialCancel})online.Controls.Add(button);
   downloadProgress=new ModernProgressBar{Location=new Point(24,204),Size=new Size(888,6),Minimum=0,Maximum=100,Style=ProgressBarStyle.Continuous,AccessibleName="官方包下载进度"};online.Controls.Add(downloadProgress);downloadStatus=LabelAt("",24,215,888,24,9,Muted);online.Controls.Add(downloadStatus);body.Controls.Add(online);
   var drop=new Card{Location=new Point(32,388),Size=new Size(936,132),AccessibleName="新版压缩包拖放区域"};drop.Paint+=(o,e)=>{using(var pen=new Pen(Theme.Border,1)){pen.DashStyle=System.Drawing.Drawing2D.DashStyle.Dash;e.Graphics.DrawRectangle(pen,12,12,drop.Width-25,drop.Height-25);}};drop.Controls.Add(LabelAt("拖入压缩包",28,29,610,36,18,null,true));drop.Controls.Add(LabelAt("手动导入  /  ZIP · 7Z · RAR",29,76,610,26,10,Muted));update=ButtonAt("选择压缩包",692,43,216,46,false,PickArchive);drop.Controls.Add(update);ArchiveDrop.AttachThemed(drop,()=>busy,UpdateArchive,Error);body.Controls.Add(drop);
   body.Controls.Add(LabelAt("安装位置："+settings.InstallRoot,34,535,932,26,10,Muted));hints.SetToolTip(drop,"整包替换，旧配置与词典不保留。");hints.SetToolTip(officialDownload,"下载官方完整包并整包替换，旧配置与词典不保留。游戏运行中只下载，退出后再安装。");
   local=LabelAt("○  本地桥服务    尚未检查",34,573,455,30,11,Muted);translation=LabelAt("○  在线翻译    尚未测试",520,573,445,30,11,Muted);body.Controls.Add(local);body.Controls.Add(translation);body.Controls.Add(LabelAt("更新记录",34,606,874,23,10,Muted,true));
   var logs=new Card{Location=new Point(32,632),Size=new Size(936,50)};logBox=new ListBox{Location=new Point(16,8),Size=new Size(901,34),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9),AccessibleName="更新记录"};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderChecks();RenderOfficial();
  }
  void RenderOfficial(){if(softwarePage){RenderSoftware();return;}if(officialStatus==null||officialStatus.IsDisposed)return;officialCheck.Enabled=!busy;officialCancel.Enabled=busy&&onlineCancellation!=null;officialCancel.Visible=onlineCancellation!=null;officialNotes.Enabled=!busy&&officialRelease!=null;bool newer=officialRelease!=null&&OfficialUpdates.IsNewer(officialRelease,settings.CurrentFolder);officialDownload.Enabled=!busy&&newer;officialDownload.Text=officialRelease!=null&&downloadedTag==officialRelease.Tag&&File.Exists(officialArchive)?"安装已下载版本":"下载并更新";if(officialRelease==null){officialStatus.Text="尚未检查官方版本";officialStatus.ForeColor=Muted;return;}Version current=OfficialUpdates.CurrentVersion(settings.CurrentFolder);officialStatus.Text=newer?"可用版本  "+officialRelease.Version+"  ·  "+(officialRelease.Size/1024d/1024d).ToString("F1")+" MB":"当前版本已是最新  ·  "+(current==null?officialRelease.Version.ToString():current.ToString());officialStatus.ForeColor=newer?Ink:Green;}
  async void CheckOfficial(){if(busy)return;onlineCancellation=new CancellationTokenSource();SetBusy(true);officialStatus.Text="正在检查官方版本…";officialStatus.ForeColor=Muted;try{var release=await Task.Run(()=>OfficialUpdates.GetLatest(onlineCancellation.Token));if(officialRelease!=null&&officialRelease.Tag!=release.Tag){officialArchive="";downloadedTag="";}officialRelease=release;officialArchive=await Task.Run(()=>DownloadCache.Find(Path.Combine(Core.DataDir,"downloads"),release));downloadedTag=String.IsNullOrEmpty(officialArchive)?"":release.Tag;Log("官方最新正式版："+release.Tag+" / "+release.Name);}catch(OperationCanceledException){Log("已取消版本检查。");downloadStatus.Text="检查已取消";}catch(Exception e){Log("检查失败："+e.Message);downloadStatus.Text=e.Message;officialRelease=null;}finally{onlineCancellation.Dispose();onlineCancellation=null;SetBusy(false);}}
  async void DownloadOfficial(){if(busy||officialRelease==null||!OfficialUpdates.IsNewer(officialRelease,settings.CurrentFolder))return;var release=officialRelease;var session=new ModDownloadSession(Bridge.GameRunning());bool downloaded=false;onlineCancellation=new CancellationTokenSource();SetBusy(true);downloadStatus.Text="正在准备下载…";try{if(downloadedTag==release.Tag&&File.Exists(officialArchive)){await Task.Run(()=>OfficialUpdates.VerifyArchive(release,officialArchive));}else{downloadProgress.Value=0;Log("下载官方完整包："+release.Name);var progress=new Progress<DownloadProgress>(p=>{if(onlineCancellation!=null&&downloadProgress!=null&&!downloadProgress.IsDisposed){downloadProgress.Value=p.Percent;downloadStatus.Text=p.Percent+"%  ·  "+(p.Received/1024d/1024d).ToString("F1")+" / "+(p.Total/1024d/1024d).ToString("F1")+" MB  ·  "+(p.BytesPerSecond/1024d/1024d).ToString("F2")+" MB/s";}});officialArchive=await Task.Run(()=>OfficialUpdates.Download(release,Path.Combine(Core.DataDir,"downloads"),onlineCancellation.Token,p=>((IProgress<DownloadProgress>)progress).Report(p),null));downloadedTag=release.Tag;await Task.Run(()=>DownloadCache.Save(Path.Combine(Core.DataDir,"downloads"),release,officialArchive));}onlineCancellation.Token.ThrowIfCancellationRequested();downloaded=true;downloadProgress.Value=100;downloadStatus.Text="下载完成  ·  SHA256 校验通过";Log("完整包已下载并通过 SHA256 校验。");}catch(OperationCanceledException){downloadStatus.Text="下载已取消，可重新下载。";Log("下载已取消，现有安装未变。");}catch(Exception e){downloadStatus.Text=e.Message;Log("下载未完成："+e.Message);officialArchive="";downloadedTag="";}finally{onlineCancellation.Dispose();onlineCancellation=null;SetBusy(false);}if(!downloaded)return;if(!session.CanInstallAutomatically(Bridge.GameRunning())){downloadStatus.Text="已下载并校验  ·  退出游戏后点击“安装已下载版本”";Log("游戏正在运行，安装包已保留，等待你退出游戏后安装。");return;}UpdateArchive(officialArchive);}
  void ShowOfficialNotes(){ShowReleaseNotes(officialRelease);}
  void ShowReleaseNotes(OfficialRelease release){if(busy||release==null)return;using(var dialog=new Form{Text="官方更新说明  ·  "+release.Tag,Size=new Size(780,620),StartPosition=FormStartPosition.CenterParent,Font=Font,BackColor=Theme.Surface,MinimizeBox=false}){var text=new TextBox{ReadOnly=true,Multiline=true,ScrollBars=ScrollBars.Vertical,Dock=DockStyle.Fill,BorderStyle=BorderStyle.None,BackColor=Theme.Surface,ForeColor=Ink,Text=release.Tag+"  /  "+release.PublishedUtc.ToLocalTime().ToString("yyyy-MM-dd")+Environment.NewLine+Environment.NewLine+release.Notes};dialog.Controls.Add(text);var footer=new Panel{Dock=DockStyle.Bottom,Height=70,BackColor=Theme.Surface};footer.Controls.Add(ButtonAt("打开官方发布页",24,12,220,44,false,()=>{try{Process.Start(new ProcessStartInfo(release.PageUrl){UseShellExecute=true});}catch(Exception e){Error(e.Message);}}));footer.Controls.Add(ButtonAt("关闭",530,12,170,44,true,()=>dialog.Close()));dialog.Controls.Add(footer);dialog.ShowDialog(this);}}
  void OpenFolder(string p){try{if(!Directory.Exists(p))throw new Exception("文件夹尚未创建。");Process.Start("explorer.exe",Core.Quote(p));}catch(Exception ex){Error(ex.Message);}}
  async void StopBridge(){if(busy)return;SetBusy(true);try{await Task.Run(()=>Bridge.Stop(settings.CurrentFolder));SyncContext();connectivity.RecordCheck(new CheckResult{Error="桥已手动停止。"},DateTime.UtcNow);RenderChecks();Log("当前版本的桥已停止。");}catch(Exception ex){Error(ex.Message);}finally{SetBusy(false);}}
  void SyncContext(){string port;try{port=Bridge.Port(settings.CurrentFolder).ToString();}catch{port="invalid";}string key=(settings.GameRoot+"|"+settings.CurrentFolder+"|"+port).ToUpperInvariant();if(key!=connectivity.Context)installation=null;connectivity.ChangeContext(key);}
  void RefreshLaunch(){bool running=Bridge.GameRunning();if(launch!=null&&!launch.IsDisposed)launch.Text=running?"检查运行状态  →":"检查并启动游戏  →";}
  async void PollBridge(){if(busy||monitoring||detecting||IsDisposed)return;monitoring=true;try{SyncContext();long revision=connectivity.Revision;string folder=settings.CurrentFolder;var result=await Task.Run(()=>Bridge.Probe(folder));if(IsDisposed||Disposing||busy)return;SyncContext();if(connectivity.ApplyProbe(result,revision,DateTime.UtcNow)){RenderChecks();RefreshLaunch();}}catch(Exception ex){if(!IsDisposed&&!Disposing)Log("状态查询未完成："+ex.Message);}finally{monitoring=false;}}
  Color StatusColor(Color color){if(Theme.IsDark)return color;if(local!=null&&local.Parent!=null&&local.Parent.BackColor==Theme.Dark){if(color==Theme.Success)return Color.FromArgb(157,219,175);if(color==Theme.Danger)return Color.FromArgb(255,156,141);return Color.FromArgb(211,222,207);}return color;}
  void RenderChecks(){if(local==null||local.IsDisposed||translation==null||translation.IsDisposed)return;DateTime now=DateTime.UtcNow;hints.SetToolTip(local,"每 15 秒刷新本地桥状态。");hints.SetToolTip(translation,"在线测试结果 10 分钟有效；桥离线或重启后需重新测试。");
   local.Text=!connectivity.Known?"○  本地桥服务    尚未检查":connectivity.LocalFresh(now)?"✓  本地桥服务    正常 · "+connectivity.ProbeUtc.ToLocalTime().ToString("HH:mm:ss"):connectivity.Local?"○  本地桥服务    状态过期，等待刷新":"✕  本地桥服务    离线 · "+connectivity.ProbeUtc.ToLocalTime().ToString("HH:mm:ss");local.ForeColor=connectivity.LocalFresh(now)?StatusColor(Theme.Success):connectivity.Known&&!connectivity.Local?StatusColor(Theme.Danger):StatusColor(Theme.Muted);
   if(connectivity.TranslationFresh(now)){translation.Text="✓  在线翻译    上次通过 "+connectivity.TranslationUtc.ToLocalTime().ToString("HH:mm:ss");translation.ForeColor=StatusColor(Theme.Success);}else{translation.ForeColor=StatusColor(Theme.Muted);translation.Text=!connectivity.LocalFresh(now)?"○  在线翻译    等待本地桥":connectivity.Translation?"○  在线翻译    上次通过 "+connectivity.TranslationUtc.ToLocalTime().ToString("HH:mm:ss")+"，需复检":!String.IsNullOrEmpty(connectivity.TranslationError)?"✕  在线翻译    最近测试未通过":"○  在线翻译    尚未测试";if(connectivity.LocalFresh(now)&&!connectivity.Translation&&!String.IsNullOrEmpty(connectivity.TranslationError))translation.ForeColor=StatusColor(Theme.Danger);}
  }
  void RenderInstallation(){if(installationStatus==null||installationStatus.IsDisposed)return;installationStatus.Text=installation==null?"○  安装文件    尚未检查":installation.Ready?"✓  安装文件    VPK 与加载配置正常":"✕  安装文件    需要处理，见诊断详情";installationStatus.ForeColor=installation==null?Muted:installation.Ready?Green:Theme.Danger;}
  void ShowDiagnostics(){if(busy)return;RhineRoute("diagnostics");ClearBody();SyncContext();importPage=false;diagnosticPage=true;body.Controls.Add(LabelAt("诊断与修复",32,24,720,42,25,null,true));version=LabelAt("所选版本  /  "+(String.IsNullOrEmpty(settings.CurrentFolder)?"尚未安装":Path.GetFileName(settings.CurrentFolder)),34,75,700,26,10,Muted);body.Controls.Add(version);settingsButton=ButtonAt("←  返回启动",800,34,168,42,false,ShowMain);body.Controls.Add(settingsButton);
   var card=new Card{Location=new Point(32,120),Size=new Size(936,200)};local=LabelAt("○  本地桥服务    尚未检查",26,26,875,32,13,Muted);translation=LabelAt("○  在线翻译    尚未测试",26,76,875,32,13,Muted);installationStatus=LabelAt("○  安装文件    尚未检查",26,126,875,32,13,Muted);card.Controls.Add(local);card.Controls.Add(translation);card.Controls.Add(installationStatus);body.Controls.Add(card);
   var game=new Card{Location=new Point(32,340),Size=new Size(936,96)};game.Controls.Add(LabelAt("游戏状态",24,15,875,25,11,null,true));gameNotice=LabelAt("尚未检查",24,49,884,40,10,Muted);game.Controls.Add(gameNotice);body.Controls.Add(game);
   update=ButtonAt("检查安装与连接",32,456,268,52,true,()=>RunDiagnostics(false));repairButton=ButtonAt("重启桥并复检",316,456,240,52,false,()=>RunDiagnostics(true));body.Controls.Add(update);body.Controls.Add(repairButton);
   body.Controls.Add(LabelAt("诊断记录",34,530,874,25,10,Muted,true));var logs=new Card{Location=new Point(32,566),Size=new Size(936,92)};logBox=new ListBox{Location=new Point(16,12),Size=new Size(901,69),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9),AccessibleName="诊断记录"};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderChecks();RenderInstallation();if(installation!=null&&!installation.Ready)Log(installation.Summary);if(!String.IsNullOrEmpty(connectivity.Error))Log(connectivity.Error);else if(!String.IsNullOrEmpty(connectivity.TranslationError))Log(connectivity.TranslationError);
  }
  async void RunDiagnostics(bool restart){if(busy)return;SetBusy(true);ResetChecks();try{var report=await Task.Run(()=>{var install=Installation.Inspect(settings);CheckResult result;try{result=Recovery.Run(settings,restart,Log,LocalState,new BridgeRuntime());}catch(Exception e){result=new CheckResult{Error=e.Message};}return Tuple.Create(install,result,GameDiagnostics.Inspect(settings));});Results(report.Item2);installation=report.Item1;RenderInstallation();if(gameNotice!=null&&!gameNotice.IsDisposed)gameNotice.Text=report.Item3.Message;Log(installation.Summary);Log(report.Item3.Message);if(!String.IsNullOrEmpty(report.Item2.Error))Log(report.Item2.Error);if(!report.Item2.Local||!report.Item2.Translation)Log("检查未全部通过，请根据上方记录处理后重试。");}catch(Exception e){Log("诊断未完成："+e.Message);connectivity.RecordCheck(new CheckResult{Error=e.Message},DateTime.UtcNow);RenderChecks();}finally{SetBusy(false);}}
  void Log(string s){if(InvokeRequired){BeginInvoke(new Action<string>(Log),s);return;}RhineLog(s);if(logBox!=null&&!logBox.IsDisposed){logBox.Items.Add(DateTime.Now.ToString("HH:mm:ss")+"  "+s);if(logBox.Items.Count>300)logBox.Items.RemoveAt(0);logBox.TopIndex=Math.Max(0,logBox.Items.Count-1);}try{Directory.CreateDirectory(Core.DataDir);File.AppendAllText(Path.Combine(Core.DataDir,"manager.log"),DateTime.Now+" "+s+Environment.NewLine);}catch{}}
  void SetBusy(bool b){busy=b;if(b)connectivity.BeginAction();SetButtons(body,!b);foreach(Control c in body.Controls)if(Object.Equals(c.Tag,"navigation"))c.Enabled=!b;UseWaitCursor=b;RenderOfficial();if(!b){RefreshLaunch();QueueStartupOffer();}}
  void SetButtons(Control parent,bool enabled){foreach(Control child in parent.Controls){if(child is Button)child.Enabled=enabled;else SetButtons(child,enabled);}}
  void ResetChecks(){if(local==null||translation==null)return;local.Text="◌  本地桥服务    正在检查…";local.ForeColor=StatusColor(Theme.Muted);translation.Text="○  在线翻译    等待本地桥…";translation.ForeColor=StatusColor(Theme.Muted);}
  void LocalState(bool ok,string err){if(InvokeRequired){BeginInvoke(new Action<bool,string>(LocalState),ok,err);return;}if(!busy||local==null||translation==null||local.IsDisposed||translation.IsDisposed)return;local.Text=ok?"✓  本地桥服务    正常":"✕  本地桥服务    失败";local.ForeColor=ok?StatusColor(Theme.Success):StatusColor(Theme.Danger);translation.Text=ok?"◌  在线翻译    正在测试随机长句…":"○  在线翻译    等待本地桥恢复";}
  void Results(CheckResult r){SyncContext();connectivity.RecordCheck(r,DateTime.UtcNow);RenderChecks();}
  void Error(string s){MessageBox.Show(this,s,"巴别塔启动器",MessageBoxButtons.OK,MessageBoxIcon.Warning);}
  void PickArchive(){using(var d=new OpenFileDialog{Title="选择官方 Windows 巴别塔新版压缩包",Filter="巴别塔压缩包|*.zip;*.7z;*.rar"})if(d.ShowDialog(this)==DialogResult.OK)UpdateArchive(d.FileName);}
  async void UpdateArchive(string archive){
   if(busy)return;if(!new[]{".zip",".7z",".rar"}.Contains(Path.GetExtension(archive).ToLowerInvariant())||!File.Exists(archive)){Error("请选择 ZIP、7Z 或 RAR 压缩包。");return;}
   if(Bridge.GameRunning()){Error("请退出 Deadlock 后再安装；已下载的压缩包会保留。");return;}if(!importPage)ShowImportPage();SetBusy(true);ResetChecks();if(downloadStatus!=null)downloadStatus.Text="正在解压、检查并安装…";
   try{
    var report=await Task.Run(()=>PackageInstaller.Install(settings,archive,new BridgeRuntime(),Bridge.GameRunning,Log,LocalState));
    SyncContext();Results(report.Check);installation=report.Installation;version.Text="当前版本  /  "+Path.GetFileName(settings.CurrentFolder);Log("新包已完整替换旧包，游戏 VPK 与加载配置检查通过。");
    if(!String.IsNullOrEmpty(report.Warning))Log(report.Warning);
    if(archive==officialArchive){try{string cache=Path.Combine(Core.DataDir,"downloads");Core.NoLinks(archive);if(Core.Under(cache,archive)){File.Delete(archive);string directory=Path.GetDirectoryName(archive);if(Directory.GetFileSystemEntries(directory).Length==0)Directory.Delete(directory);}}catch(Exception cleanup){Log("下载缓存暂未清理："+cleanup.Message);}officialArchive="";downloadedTag="";}
    if(downloadStatus!=null)downloadStatus.Text="更新完成  ·  本地桥、翻译接口与安装文件检查通过";SetBusy(false);if(String.IsNullOrEmpty(report.Warning))ConfirmLaunch();else Error(report.Warning);
   }catch(Exception ex){Log("安装未完成："+ex.Message);Results(new CheckResult{Error=ex.Message});if(downloadStatus!=null)downloadStatus.Text="安装未完成，见更新记录";SetBusy(false);Error("更新未完成。旧版本文件保留，恢复结果请看更新记录。\n\n"+ex.Message);}
   finally{if(busy)SetBusy(false);}
  }
  async void CheckLaunch(){if(busy)return;if(Bridge.GameRunning()){ShowDiagnostics();RunDiagnostics(false);return;}if(!Core.IsPackage(settings.CurrentFolder)){Error("请先导入完整压缩包，或在路径设置中选择已有版本。");return;}SetBusy(true);ResetChecks();try{installation=await Task.Run(()=>Installation.Inspect(settings));RenderInstallation();if(!installation.Ready){Log(installation.Summary);SetBusy(false);ShowDiagnostics();Error("安装检查未通过，已打开诊断页。\n\n"+installation.Summary);return;}CheckResult r=await Task.Run(()=>Recovery.Run(settings,false,Log,LocalState,new BridgeRuntime()));Results(r);SetBusy(false);if(r.Local&&r.Translation)ConfirmLaunch();else{ShowDiagnostics();Error("检查未通过，可在诊断页重试。\n\n"+r.Error);}}catch(Exception e){Results(new CheckResult{Error=e.Message});SetBusy(false);Log(e.Message);ShowDiagnostics();Error(e.Message);}}
  void ConfirmLaunch(){if(installation==null||!installation.Ready||!connectivity.TranslationFresh(DateTime.UtcNow)){Error("检查结果已失效，请重新检查后启动。");return;}if(rhineReady){rhineConfirm=true;return;}using(var dialog=new Form{Text="启动前检查完成",Size=new Size(550,383),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font,BackColor=Theme.Surface}){dialog.Controls.Add(LabelAt("检查已通过，可以启动游戏",27,23,490,38,17,null,true));dialog.Controls.Add(LabelAt("✓   本地桥服务正常",30,80,480,34,13,Green,true));dialog.Controls.Add(LabelAt("✓   翻译接口正常",30,123,480,34,13,Green,true));dialog.Controls.Add(LabelAt("✓   Mod 文件与加载配置正常",30,165,480,34,13,Green,true));dialog.Controls.Add(LabelAt("游戏载入后，在 /tr 面板确认实际连接。",30,209,470,35,10,Muted));var yes=ButtonAt("启动游戏",30,264,210,48,true,()=>{dialog.DialogResult=DialogResult.OK;dialog.Close();});var no=ButtonAt("暂不启动",270,264,210,48,false,()=>{dialog.DialogResult=DialogResult.Cancel;dialog.Close();});dialog.Controls.Add(yes);dialog.Controls.Add(no);dialog.CancelButton=no;if(dialog.ShowDialog(this)==DialogResult.OK){try{if(!connectivity.TranslationFresh(DateTime.UtcNow))throw new Exception("检查结果已失效，请重新检查。");var latestInstall=Installation.Inspect(settings);if(!latestInstall.Ready)throw new Exception(latestInstall.Summary);string steam=Bridge.Steam();if(steam==null){using(var picker=new OpenFileDialog{Title="选择 Steam.exe",Filter="Steam|steam.exe"}){if(picker.ShowDialog(this)!=DialogResult.OK)return;steam=picker.FileName;}}Bridge.LaunchGame(steam);Log("已请求 Steam 启动 Deadlock，携带 -console -condebug。");Log("本地桥保持后台运行；游戏内连接请在加载后检查 /tr 面板。");}catch(Exception ex){Error(ex.Message);}}}}
 }
 static class Program {
  [STAThread]static void Main(){try{RhineRuntime.Prepare();Run();}catch(Exception error){MessageBox.Show(error.Message,"巴别塔启动器");}}
  [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
  static void Run(){try{using(var mutex=new Mutex(false,"Local\\BabelTowerLauncher")){bool owned;try{owned=mutex.WaitOne(0,false);}catch(AbandonedMutexException){owned=true;}if(!owned){MessageBox.Show("巴别塔启动器已在运行，请切换到已有窗口。");return;}try{Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.ThreadException+=(s,e)=>MessageBox.Show(e.Exception.Message,"巴别塔启动器");MainWindow.RhineEnabled=true;var window=new MainWindow();window.EnableRhine();Application.Run(window);}finally{mutex.ReleaseMutex();}}}catch(Exception ex){MessageBox.Show("管理器无法打开："+ex.Message,"巴别塔启动器");}}
 }
}




