using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace BabelManager {
 public class MainWindow:Form {
  readonly Color Navy=Theme.Background, Blue=Theme.Accent, Green=Theme.Success, Ink=Theme.Text, Muted=Theme.Muted;
  Settings settings;Panel body;Label local,translation,version;ListBox logBox;Button update,launch,settingsButton;bool busy,detecting,importPage,diagnosticPage,monitoring;Action pendingDetection;
  readonly ToolTip hints=new ToolTip{AutoPopDelay=12000};readonly Connectivity connectivity=new Connectivity();readonly System.Windows.Forms.Timer heartbeat=new System.Windows.Forms.Timer{Interval=15000};InstallationResult installation;Label installationStatus,gameNotice;Button diagnosticButton,repairButton;
  public MainWindow(){settings=Core.Load()??new Settings();Text="巴别塔启动器";ClientSize=new Size(1000,760);MinimumSize=new Size(1016,799);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Microsoft YaHei UI",10);BackColor=Theme.Background;AutoScaleMode=AutoScaleMode.Dpi;
   string icon=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","app.ico");if(File.Exists(icon))Icon=new Icon(icon);ShowIcon=false;
   var header=new Panel{Dock=DockStyle.Top,Height=72,BackColor=Theme.Surface};
   header.Controls.Add(LabelAt("巴别塔启动器",32,15,470,36,22,Theme.Text,true));
   header.Paint+=(o,e)=>{using(var p=new Pen(Theme.Text,1))e.Graphics.DrawLine(p,32,66,968,66);using(var b=new SolidBrush(Theme.Accent))e.Graphics.FillRectangle(b,32,66,86,4);};Controls.Add(header);
   body=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Background};Controls.Add(body);body.BringToFront();heartbeat.Tick+=(o,e)=>PollBridge();FormClosed+=(o,e)=>{heartbeat.Stop();heartbeat.Dispose();hints.Dispose();};Shown+=(o,e)=>{heartbeat.Start();PollBridge();var action=pendingDetection;pendingDetection=null;if(action!=null)action();};FormClosing+=(o,e)=>{if(busy){e.Cancel=true;MessageBox.Show(this,"正在执行检查或更新，请等待完成后关闭。","处理中");}};
   if(Core.IsGame(settings.GameRoot)&&Directory.Exists(settings.InstallRoot))ShowMain();else ShowSetup();
  }
  Label LabelAt(string text,int x,int y,int width,int height,int size=10,Color? color=null,bool bold=false){return new Label{BackColor=Color.Transparent,Text=text,Location=new Point(x,y),Size=new Size(width,height),ForeColor=color??Ink,Font=new Font(Font.FontFamily,size,bold?FontStyle.Bold:FontStyle.Regular)};}
  Button ButtonAt(string text,int x,int y,int w,int h,bool primary,Action click){var b=new ModernButton{Text=text,Location=new Point(x,y),Size=new Size(w,h),Primary=primary,BackColor=Theme.Surface,ForeColor=primary?Theme.Background:Ink,AccessibleName=text};b.Click+=(o,e)=>click();return b;}
  string PickFolder(string caption,string selected=""){using(var d=new FolderBrowserDialog{Description=caption,SelectedPath=selected,ShowNewFolderButton=true})return d.ShowDialog(this)==DialogResult.OK?d.SelectedPath:null;}
  void ClearBody(){foreach(Control c in body.Controls.Cast<Control>().ToArray())c.Dispose();local=translation=installationStatus=gameNotice=null;logBox=null;launch=update=settingsButton=diagnosticButton=repairButton=null;}
  void ShowSetup(){ClearBody();diagnosticPage=importPage=false;body.Controls.Add(LabelAt(Core.IsGame(settings.GameRoot)?"路径设置":"首次设置",30,22,650,38,20,null,true));
   ComboBox game=null,current=null;TextBox root=null;var status=LabelAt("",32,454,874,48,10,Muted);body.Controls.Add(status);
   game=ChoiceField("游戏目录",108,settings.GameRoot,"Deadlock 根目录，包含 game 文件夹。",()=>DetectPaths(game,root,current,status,"game"));
   root=Field("巴别塔安装目录",223,settings.InstallRoot,"用于保存巴别塔各版本。");
   current=ChoiceField("已有版本（可选）",338,settings.CurrentFolder,"未安装可留空。",()=>DetectPaths(game,root,current,status,"mod"));
   var detectAll=ButtonAt("一键自动检测",740,23,166,38,false,()=>DetectPaths(game,root,current,status,"all"));detectAll.Tag="detect";body.Controls.Add(detectAll);
   var save=ButtonAt("保存",32,516,245,48,true,()=>{if(detecting)return;try{var next=new Settings{GameRoot=game.Text.Trim(),InstallRoot=root.Text.Trim(),CurrentFolder=current.Text.Trim()};Core.ValidateSettings(next);if(!String.IsNullOrEmpty(next.CurrentFolder)&&(!Core.IsPackage(next.CurrentFolder)||!Core.Under(next.InstallRoot,next.CurrentFolder)))throw new Exception("已有版本必须是所选安装文件夹里面的完整巴别塔文件夹。请先把它移进去，再选择。");Directory.CreateDirectory(next.InstallRoot);if(!String.IsNullOrEmpty(next.CurrentFolder)){var vpks=Core.GameVpks(next);next.VpkPath=vpks.FirstOrDefault()??"";}Core.Save(next);settings=next;ShowMain();}catch(Exception ex){Error(ex.Message);}});save.Tag="detect";body.Controls.Add(save);
   if(Core.IsGame(settings.GameRoot))body.Controls.Add(ButtonAt("返回",300,516,100,48,false,()=>{if(!detecting)ShowMain();}));
   if(!Core.IsGame(settings.GameRoot)||!Core.IsPackage(settings.CurrentFolder)){Action detect=()=>DetectPaths(game,root,current,status,"all");if(IsHandleCreated)BeginInvoke(detect);else pendingDetection=detect;}
  }
  ComboBox ChoiceField(string title,int y,string value,string help,Action detect){body.Controls.Add(LabelAt(title,32,y,550,28,12,null,true));var t=new ComboBox{BackColor=Theme.Surface,ForeColor=Theme.Text,FlatStyle=FlatStyle.Flat,Text=value,Location=new Point(32,y+37),Size=new Size(705,32),DropDownStyle=ComboBoxStyle.DropDown,AutoCompleteMode=AutoCompleteMode.SuggestAppend,AutoCompleteSource=AutoCompleteSource.ListItems,DropDownWidth=800};body.Controls.Add(t);var auto=ButtonAt("自动检测",606,y-3,130,31,false,detect);auto.Tag="detect";body.Controls.Add(auto);body.Controls.Add(ButtonAt("浏览…",756,y+33,150,37,false,()=>{string p=PickFolder(title,t.Text);if(p!=null)t.Text=p;}));body.Controls.Add(LabelAt(help,32,y+78,850,30,10,Muted));return t;}
  static void Choices(ComboBox box,string[] paths,string selected){box.Items.Clear();box.Items.AddRange(paths.Cast<object>().ToArray());box.Text=selected;}
  async void DetectPaths(ComboBox game,TextBox root,ComboBox current,Label status,string which){if(detecting||game==null||current==null||game.IsDisposed)return;detecting=true;foreach(Control b in body.Controls)if(Object.Equals(b.Tag,"detect"))b.Enabled=false;status.Text="正在检测 Steam 游戏库、常见安装位置与完整的巴别塔目录…";var inputs=new Settings{GameRoot=game.Text.Trim(),InstallRoot=root.Text.Trim(),CurrentFolder=current.Text.Trim()};try{var result=await Task.Run(()=>Discovery.Detect(inputs));if(game.IsDisposed||current.IsDisposed)return;if(which!="mod")Choices(game,result.Games.ToArray(),result.Game);if(which!="game"){Choices(current,result.Packages.ToArray(),result.Package);root.Text=result.InstallRoot;}status.Text="检测完成：找到 "+result.Games.Count+" 个游戏目录、"+result.Packages.Count+" 个巴别塔版本。"+(result.Games.Count==0?"未找到游戏，请手动浏览。":result.Packages.Count==0?"尚未找到已有版本，可先保存再导入压缩包。":"多个结果可在下拉框选择，确认后保存。");}catch(Exception ex){if(!status.IsDisposed)status.Text="检测未完成，可手动浏览："+ex.Message;}finally{detecting=false;if(!body.IsDisposed)foreach(Control b in body.Controls)if(Object.Equals(b.Tag,"detect"))b.Enabled=true;}}
  TextBox Field(string title,int y,string value,string help){body.Controls.Add(LabelAt(title,32,y,850,28,12,null,true));var t=new TextBox{BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.FixedSingle,Text=value,Location=new Point(32,y+37),Size=new Size(705,32),Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};body.Controls.Add(t);body.Controls.Add(ButtonAt("浏览…",756,y+33,150,37,false,()=>{string p=PickFolder(title,t.Text);if(p!=null)t.Text=p;}));body.Controls.Add(LabelAt(help,32,y+78,850,30,10,Muted));return t;}
  void ShowMain(){ClearBody();importPage=diagnosticPage=false;SyncContext();
   var rail=new Panel{Location=new Point(24,26),Size=new Size(102,654),BackColor=Theme.Surface,Tag="navigation",AccessibleName="主导航"};
   rail.Paint+=(o,e)=>{using(var p=new Pen(Theme.Border))e.Graphics.DrawLine(p,101,0,101,654);};
   var home=ButtonAt("启动",10,20,80,48,true,()=>{if(!busy)ShowMain();});home.AccessibleName="启动（当前页面）";rail.Controls.Add(home);
   rail.Controls.Add(ButtonAt("更新",10,94,80,48,false,ShowImportPage));
   diagnosticButton=ButtonAt("诊断",10,168,80,48,false,ShowDiagnostics);rail.Controls.Add(diagnosticButton);
   settingsButton=ButtonAt("设置",10,242,80,48,false,ShowSetup);rail.Controls.Add(settingsButton);
   rail.Controls.Add(ButtonAt("文件夹",10,584,80,48,false,()=>OpenFolder(settings.InstallRoot)));body.Controls.Add(rail);
   var name=LabelAt("DEADLOCK",150,23,818,70,44,Theme.Text,true);name.Font=new Font("Bahnschrift",44,FontStyle.Bold);body.Controls.Add(name);
   version=LabelAt("当前版本 / "+(String.IsNullOrEmpty(settings.CurrentFolder)?"尚未安装":Path.GetFileName(settings.CurrentFolder)),154,101,810,29,11,Theme.Text);body.Controls.Add(version);
   var check=new Card{Location=new Point(150,151),Size=new Size(818,240),Terrain=true,AccessibleName="连接状态"};
   check.Controls.Add(LabelAt("连接状态",24,19,410,32,17,Theme.Text,true));
   local=LabelAt("○  本地桥服务    尚未检查",24,74,436,32,12,Muted);check.Controls.Add(local);
   translation=LabelAt("○  在线翻译    尚未测试",24,129,436,32,12,Muted);check.Controls.Add(translation);
   installationStatus=LabelAt("○  安装文件    尚未检查",24,184,436,32,11,Muted);check.Controls.Add(installationStatus);
   check.Paint+=(o,e)=>{using(var p=new Pen(Theme.Border,1)){e.Graphics.DrawLine(p,24,113,450,113);e.Graphics.DrawLine(p,24,168,450,168);}};body.Controls.Add(check);
   var dock=new Card{Location=new Point(150,409),Size=new Size(818,96),Hero=true,AccessibleName="启动操作"};
   dock.Controls.Add(ButtonAt("桥日志",18,26,115,44,false,()=>{if(!String.IsNullOrEmpty(settings.CurrentFolder))OpenFolder(Path.Combine(settings.CurrentFolder,"logs"));}));dock.Controls.Add(ButtonAt("停止桥",147,26,115,44,false,StopBridge));
   launch=ButtonAt("检查并启动游戏  →",286,16,506,64,true,CheckLaunch);launch.Font=new Font(Font.FontFamily,18,FontStyle.Bold);dock.Controls.Add(launch);body.Controls.Add(dock);
   body.Controls.Add(LabelAt("运行记录",154,527,810,22,10,Muted,true));
   var logs=new Card{Location=new Point(150,560),Size=new Size(818,120)};logBox=new ListBox{Location=new Point(12,10),Size=new Size(790,98),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9),AccessibleName="运行记录"};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderChecks();RenderInstallation();RefreshLaunch();
   Log("游戏目录："+settings.GameRoot);Log("安装目录："+settings.InstallRoot);if(!String.IsNullOrEmpty(settings.CurrentFolder))Log("当前目录："+settings.CurrentFolder);
  }
  void ShowImportPage(){if(busy)return;ClearBody();importPage=true;diagnosticPage=false;launch=null;
   body.Controls.Add(LabelAt("版本更新",32,24,720,42,25,null,true));version=LabelAt("当前版本  /  "+(String.IsNullOrEmpty(settings.CurrentFolder)?"尚未安装":Path.GetFileName(settings.CurrentFolder)),34,75,700,26,10,Muted);body.Controls.Add(version);settingsButton=ButtonAt("←  返回启动",800,34,168,42,false,()=>{if(!busy)ShowMain();});body.Controls.Add(settingsButton);
   var drop=new Card{Location=new Point(32,120),Size=new Size(936,260),AccessibleName="新版压缩包拖放区域"};drop.Paint+=(o,e)=>{using(var pen=new Pen(Theme.Border,1)){pen.DashStyle=System.Drawing.Drawing2D.DashStyle.Dash;e.Graphics.DrawRectangle(pen,18,18,drop.Width-37,drop.Height-37);}};
   var title=LabelAt("拖入压缩包",48,44,840,47,24,null,true);title.TextAlign=ContentAlignment.MiddleCenter;drop.Controls.Add(title);var help=LabelAt("ZIP / 7Z / RAR",48,108,840,31,11,Muted);help.TextAlign=ContentAlignment.MiddleCenter;drop.Controls.Add(help);update=ButtonAt("选择压缩包",342,165,252,52,true,PickArchive);drop.Controls.Add(update);ArchiveDrop.Attach(drop,()=>busy,UpdateArchive,Error,Theme.AccentTint);body.Controls.Add(drop);
   var info=new Card{Location=new Point(32,400),Size=new Size(936,76)};info.Controls.Add(LabelAt("安装位置："+settings.InstallRoot,24,12,888,27,11,null,true));info.Controls.Add(LabelAt("整包替换，旧配置与词典不保留。",24,46,888,27,10,Muted));body.Controls.Add(info);
   local=LabelAt("○  本地桥服务    尚未检查",34,496,455,30,11,Muted);translation=LabelAt("○  在线翻译    尚未测试",520,496,445,30,11,Muted);body.Controls.Add(local);body.Controls.Add(translation);body.Controls.Add(LabelAt("更新记录",34,546,874,25,10,Muted,true));
   var logs=new Card{Location=new Point(32,580),Size=new Size(936,78)};logBox=new ListBox{Location=new Point(16,12),Size=new Size(901,55),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9),AccessibleName="更新记录"};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderChecks();
  }
  void OpenFolder(string p){try{if(!Directory.Exists(p))throw new Exception("文件夹尚未创建。");Process.Start("explorer.exe",Core.Quote(p));}catch(Exception ex){Error(ex.Message);}}
  async void StopBridge(){if(busy)return;SetBusy(true);try{await Task.Run(()=>Bridge.Stop(settings.CurrentFolder));SyncContext();connectivity.RecordCheck(new CheckResult{Error="桥已手动停止。"},DateTime.UtcNow);RenderChecks();Log("当前版本的桥已停止。");}catch(Exception ex){Error(ex.Message);}finally{SetBusy(false);}}
  void SyncContext(){string port;try{port=Bridge.Port(settings.CurrentFolder).ToString();}catch{port="invalid";}string key=(settings.GameRoot+"|"+settings.CurrentFolder+"|"+port).ToUpperInvariant();if(key!=connectivity.Context)installation=null;connectivity.ChangeContext(key);}
  void RefreshLaunch(){bool running=Bridge.GameRunning();if(launch!=null&&!launch.IsDisposed)launch.Text=running?"检查运行状态  →":"检查并启动游戏  →";}
  async void PollBridge(){if(busy||monitoring||detecting||IsDisposed)return;monitoring=true;try{SyncContext();long revision=connectivity.Revision;string folder=settings.CurrentFolder;var result=await Task.Run(()=>Bridge.Probe(folder));if(IsDisposed||Disposing||busy)return;SyncContext();if(connectivity.ApplyProbe(result,revision,DateTime.UtcNow)){RenderChecks();RefreshLaunch();}}catch(Exception ex){if(!IsDisposed&&!Disposing)Log("状态查询未完成："+ex.Message);}finally{monitoring=false;}}
  Color StatusColor(Color color){if(local!=null&&local.Parent!=null&&local.Parent.BackColor==Theme.Dark){if(color==Theme.Success)return Color.FromArgb(157,219,175);if(color==Theme.Danger)return Color.FromArgb(255,156,141);return Color.FromArgb(211,222,207);}return color;}
  void RenderChecks(){if(local==null||local.IsDisposed||translation==null||translation.IsDisposed)return;DateTime now=DateTime.UtcNow;hints.SetToolTip(local,"每 15 秒刷新本地桥状态。");hints.SetToolTip(translation,"在线测试结果 10 分钟有效；桥离线或重启后需重新测试。");
   local.Text=!connectivity.Known?"○  本地桥服务    尚未检查":connectivity.LocalFresh(now)?"✓  本地桥服务    正常 · "+connectivity.ProbeUtc.ToLocalTime().ToString("HH:mm:ss"):connectivity.Local?"○  本地桥服务    状态过期，等待刷新":"✕  本地桥服务    离线 · "+connectivity.ProbeUtc.ToLocalTime().ToString("HH:mm:ss");local.ForeColor=connectivity.LocalFresh(now)?StatusColor(Theme.Success):connectivity.Known&&!connectivity.Local?StatusColor(Theme.Danger):StatusColor(Theme.Muted);
   if(connectivity.TranslationFresh(now)){translation.Text="✓  在线翻译    上次通过 "+connectivity.TranslationUtc.ToLocalTime().ToString("HH:mm:ss");translation.ForeColor=StatusColor(Theme.Success);}else{translation.ForeColor=StatusColor(Theme.Muted);translation.Text=!connectivity.LocalFresh(now)?"○  在线翻译    等待本地桥":connectivity.Translation?"○  在线翻译    上次通过 "+connectivity.TranslationUtc.ToLocalTime().ToString("HH:mm:ss")+"，需复检":!String.IsNullOrEmpty(connectivity.TranslationError)?"✕  在线翻译    最近测试未通过":"○  在线翻译    尚未测试";if(connectivity.LocalFresh(now)&&!connectivity.Translation&&!String.IsNullOrEmpty(connectivity.TranslationError))translation.ForeColor=StatusColor(Theme.Danger);}
  }
  void RenderInstallation(){if(installationStatus==null||installationStatus.IsDisposed)return;installationStatus.Text=installation==null?"○  安装文件    尚未检查":installation.Ready?"✓  安装文件    VPK 与加载配置正常":"✕  安装文件    需要处理，见诊断详情";installationStatus.ForeColor=installation==null?Muted:installation.Ready?Green:Theme.Danger;}
  void ShowDiagnostics(){if(busy)return;ClearBody();SyncContext();importPage=false;diagnosticPage=true;body.Controls.Add(LabelAt("诊断与修复",32,24,720,42,25,null,true));version=LabelAt("所选版本  /  "+(String.IsNullOrEmpty(settings.CurrentFolder)?"尚未安装":Path.GetFileName(settings.CurrentFolder)),34,75,700,26,10,Muted);body.Controls.Add(version);settingsButton=ButtonAt("←  返回启动",800,34,168,42,false,ShowMain);body.Controls.Add(settingsButton);
   var card=new Card{Location=new Point(32,120),Size=new Size(936,200)};local=LabelAt("○  本地桥服务    尚未检查",26,26,875,32,13,Muted);translation=LabelAt("○  在线翻译    尚未测试",26,76,875,32,13,Muted);installationStatus=LabelAt("○  安装文件    尚未检查",26,126,875,32,13,Muted);card.Controls.Add(local);card.Controls.Add(translation);card.Controls.Add(installationStatus);body.Controls.Add(card);
   var game=new Card{Location=new Point(32,340),Size=new Size(936,96)};game.Controls.Add(LabelAt("游戏状态",24,15,875,25,11,null,true));gameNotice=LabelAt("尚未检查",24,49,884,40,10,Muted);game.Controls.Add(gameNotice);body.Controls.Add(game);
   update=ButtonAt("检查安装与连接",32,456,268,52,true,()=>RunDiagnostics(false));repairButton=ButtonAt("重启桥并复检",316,456,240,52,false,()=>RunDiagnostics(true));body.Controls.Add(update);body.Controls.Add(repairButton);
   body.Controls.Add(LabelAt("诊断记录",34,530,874,25,10,Muted,true));var logs=new Card{Location=new Point(32,566),Size=new Size(936,92)};logBox=new ListBox{Location=new Point(16,12),Size=new Size(901,69),HorizontalScrollbar=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Microsoft YaHei UI",9),AccessibleName="诊断记录"};logs.Controls.Add(logBox);body.Controls.Add(logs);RenderChecks();RenderInstallation();if(installation!=null&&!installation.Ready)Log(installation.Summary);if(!String.IsNullOrEmpty(connectivity.Error))Log(connectivity.Error);else if(!String.IsNullOrEmpty(connectivity.TranslationError))Log(connectivity.TranslationError);
  }
  async void RunDiagnostics(bool restart){if(busy)return;SetBusy(true);ResetChecks();try{var report=await Task.Run(()=>{var install=Installation.Inspect(settings);CheckResult result;try{result=Recovery.Run(settings,restart,Log,LocalState,new BridgeRuntime());}catch(Exception e){result=new CheckResult{Error=e.Message};}return Tuple.Create(install,result,GameDiagnostics.Inspect(settings));});Results(report.Item2);installation=report.Item1;RenderInstallation();if(gameNotice!=null&&!gameNotice.IsDisposed)gameNotice.Text=report.Item3.Message;Log(installation.Summary);Log(report.Item3.Message);if(!String.IsNullOrEmpty(report.Item2.Error))Log(report.Item2.Error);if(!report.Item2.Local||!report.Item2.Translation)Log("检查未全部通过，请根据上方记录处理后重试。");}catch(Exception e){Log("诊断未完成："+e.Message);connectivity.RecordCheck(new CheckResult{Error=e.Message},DateTime.UtcNow);RenderChecks();}finally{SetBusy(false);}}
  void Log(string s){if(InvokeRequired){BeginInvoke(new Action<string>(Log),s);return;}if(logBox!=null&&!logBox.IsDisposed){logBox.Items.Add(DateTime.Now.ToString("HH:mm:ss")+"  "+s);if(logBox.Items.Count>300)logBox.Items.RemoveAt(0);logBox.TopIndex=Math.Max(0,logBox.Items.Count-1);}try{Directory.CreateDirectory(Core.DataDir);File.AppendAllText(Path.Combine(Core.DataDir,"manager.log"),DateTime.Now+" "+s+Environment.NewLine);}catch{}}
  void SetBusy(bool b){busy=b;if(b)connectivity.BeginAction();foreach(var button in new[]{settingsButton,update,launch,diagnosticButton,repairButton})if(button!=null&&!button.IsDisposed)button.Enabled=!b;foreach(Control c in body.Controls)if(Object.Equals(c.Tag,"navigation"))c.Enabled=!b;UseWaitCursor=b;if(!b)RefreshLaunch();}
  void ResetChecks(){if(local==null||translation==null)return;local.Text="◌  本地桥服务    正在检查…";local.ForeColor=StatusColor(Theme.Muted);translation.Text="○  在线翻译    等待本地桥…";translation.ForeColor=StatusColor(Theme.Muted);}
  void LocalState(bool ok,string err){if(InvokeRequired){BeginInvoke(new Action<bool,string>(LocalState),ok,err);return;}if(!busy||local==null||translation==null||local.IsDisposed||translation.IsDisposed)return;local.Text=ok?"✓  本地桥服务    正常":"✕  本地桥服务    失败";local.ForeColor=ok?StatusColor(Theme.Success):StatusColor(Theme.Danger);translation.Text=ok?"◌  在线翻译    正在测试随机长句…":"○  在线翻译    等待本地桥恢复";}
  void Results(CheckResult r){SyncContext();connectivity.RecordCheck(r,DateTime.UtcNow);RenderChecks();}
  void Error(string s){MessageBox.Show(this,s,"巴别塔启动器",MessageBoxButtons.OK,MessageBoxIcon.Warning);}
  void PickArchive(){using(var d=new OpenFileDialog{Title="选择官方 Windows 巴别塔新版压缩包",Filter="巴别塔压缩包|*.zip;*.7z;*.rar"})if(d.ShowDialog(this)==DialogResult.OK)UpdateArchive(d.FileName);}
  async void UpdateArchive(string archive){if(busy)return;if(!new[]{".zip",".7z",".rar"}.Contains(Path.GetExtension(archive).ToLowerInvariant())||!File.Exists(archive)){Error("请选择 ZIP、7Z 或 RAR 压缩包。");return;}if(Bridge.GameRunning()){Error("更新前请先完全退出 Deadlock。");return;}if(!importPage)ShowImportPage();SetBusy(true);ResetChecks();string stage="",fresh="";bool committed=false,freshCreated=false;string old=settings.CurrentFolder;bool stoppedOld=false;CheckResult newResult=null;
   try{
    string warning=await Task.Run(()=>{Core.ValidateSettings(settings);stage=Core.Child(settings.InstallRoot,".bt-stage-"+Guid.NewGuid().ToString("N"));Log("解压新版："+Path.GetFileName(archive));Core.Extract(archive,stage);string pkg=Core.FindPackage(stage);string v=Core.VersionOf(archive,pkg);if(!Core.IsBabelVpk(Path.Combine(pkg,"pak01_dir.vpk")))throw new Exception("新版 VPK 不包含巴别塔聊天资源，更新已取消。");fresh=Core.Child(settings.InstallRoot,"BabelTower-"+v);if(Directory.Exists(fresh))throw new Exception("目标版本文件夹已存在："+fresh+"。请使用不同的新版本压缩包。");Log("安装新版到："+fresh);Directory.Move(pkg,fresh);freshCreated=true;if(!String.IsNullOrEmpty(old)){stoppedOld=Bridge.Processes(old).Count>0;Bridge.Stop(old);}Log("检查新版的桥和翻译接口；此时尚未改动游戏 VPK。");string w=Core.Commit(settings,fresh,()=>{Bridge.Start(fresh,settings,Log);var r=Bridge.Check(fresh,Log,LocalState);newResult=r;if(!r.Local||!r.Translation)throw new Exception(r.Error);if(Bridge.GameRunning())throw new Exception("检测到游戏正在启动，请退出游戏后重试。");},true);committed=true;return w;});
    SyncContext();if(newResult!=null)Results(newResult);installation=await Task.Run(()=>Installation.Inspect(settings));version.Text="当前版本："+Path.GetFileName(settings.CurrentFolder);Log("更新完成。新包完整替换旧包，游戏 VPK 已换新。");if(!String.IsNullOrEmpty(warning))Log(warning);SetBusy(false);if(!installation.Ready){ShowDiagnostics();Log(installation.Summary);Error("新版已安装，但游戏加载检查未通过。\n\n"+installation.Summary);}else if(String.IsNullOrEmpty(warning))ConfirmLaunch();else Error(warning);
   }catch(Exception ex){Log("更新失败："+ex.Message);if(!committed&&freshCreated&&!String.IsNullOrEmpty(fresh)&&Directory.Exists(fresh)){try{Bridge.Stop(fresh);DeleteTemporary(fresh);}catch(Exception cleanup){Log("新目录清理失败，请检查："+cleanup.Message);}}if(stoppedOld&&!committed&&Core.IsPackage(old)){try{Task.Run(()=>Bridge.Start(old,settings,Log)).GetAwaiter().GetResult();Log("已恢复旧版本桥。");}catch(Exception resume){Log("旧版本文件仍保留；桥重启失败："+resume.Message);}}Results(new CheckResult{Error=ex.Message});SetBusy(false);Error("更新未完成，旧版本已保留。\n\n"+ex.Message);
   }finally{if(!String.IsNullOrEmpty(stage)&&Directory.Exists(stage)){try{DeleteTemporary(stage);}catch(Exception ex){Log("临时目录待清理："+ex.Message);}}if(busy)SetBusy(false);}
  }
  void DeleteTemporary(string p){Core.NoLinks(p);if(!Core.Under(settings.InstallRoot,p))throw new Exception("拒绝清理安装目录以外的文件夹。");Directory.Delete(p,true);}
  async void CheckLaunch(){if(busy)return;if(Bridge.GameRunning()){ShowDiagnostics();RunDiagnostics(false);return;}if(!Core.IsPackage(settings.CurrentFolder)){Error("请先导入完整压缩包，或在路径设置中选择已有版本。");return;}SetBusy(true);ResetChecks();try{installation=await Task.Run(()=>Installation.Inspect(settings));RenderInstallation();if(!installation.Ready){Log(installation.Summary);SetBusy(false);ShowDiagnostics();Error("安装检查未通过，已打开诊断页。\n\n"+installation.Summary);return;}CheckResult r=await Task.Run(()=>Recovery.Run(settings,false,Log,LocalState,new BridgeRuntime()));Results(r);SetBusy(false);if(r.Local&&r.Translation)ConfirmLaunch();else{ShowDiagnostics();Error("检查未通过，可在诊断页重试。\n\n"+r.Error);}}catch(Exception e){Results(new CheckResult{Error=e.Message});SetBusy(false);Log(e.Message);ShowDiagnostics();Error(e.Message);}}
  void ConfirmLaunch(){if(installation==null||!installation.Ready||!connectivity.TranslationFresh(DateTime.UtcNow)){Error("检查结果已失效，请重新检查后启动。");return;}using(var dialog=new Form{Text="启动前检查完成",Size=new Size(550,383),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font,BackColor=Theme.Surface}){dialog.Controls.Add(LabelAt("检查已通过，可以启动游戏",27,23,490,38,17,null,true));dialog.Controls.Add(LabelAt("✓   本地桥服务正常",30,80,480,34,13,Green,true));dialog.Controls.Add(LabelAt("✓   翻译接口正常",30,123,480,34,13,Green,true));dialog.Controls.Add(LabelAt("✓   Mod 文件与加载配置正常",30,165,480,34,13,Green,true));dialog.Controls.Add(LabelAt("游戏载入后，在 /tr 面板确认实际连接。",30,209,470,35,10,Muted));var yes=ButtonAt("启动游戏",30,264,210,48,true,()=>{dialog.DialogResult=DialogResult.OK;dialog.Close();});var no=ButtonAt("暂不启动",270,264,210,48,false,()=>{dialog.DialogResult=DialogResult.Cancel;dialog.Close();});dialog.Controls.Add(yes);dialog.Controls.Add(no);dialog.CancelButton=no;if(dialog.ShowDialog(this)==DialogResult.OK){try{if(!connectivity.TranslationFresh(DateTime.UtcNow))throw new Exception("检查结果已失效，请重新检查。");var latestInstall=Installation.Inspect(settings);if(!latestInstall.Ready)throw new Exception(latestInstall.Summary);string steam=Bridge.Steam();if(steam==null){using(var picker=new OpenFileDialog{Title="选择 Steam.exe",Filter="Steam|steam.exe"}){if(picker.ShowDialog(this)!=DialogResult.OK)return;steam=picker.FileName;}}Bridge.LaunchGame(steam);Log("已请求 Steam 启动 Deadlock，携带 -console -condebug。");Log("本地桥保持后台运行；游戏内连接请在加载后检查 /tr 面板。");}catch(Exception ex){Error(ex.Message);}}}}
 }
 static class Program {
  [STAThread]static void Main(){try{using(var mutex=new Mutex(false,"Local\\BabelTowerManagerMirror")){bool owned;try{owned=mutex.WaitOne(0,false);}catch(AbandonedMutexException){owned=true;}if(!owned){MessageBox.Show("巴别塔启动器已在运行，请切换到已有窗口。");return;}try{Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.ThreadException+=(s,e)=>MessageBox.Show(e.Exception.Message,"巴别塔启动器");Application.Run(new MainWindow());}finally{mutex.ReleaseMutex();}}}catch(Exception ex){MessageBox.Show("管理器无法打开："+ex.Message,"巴别塔启动器");}}
 }
}
